# Test source files for TKG3d
set(OCCT_TKG3d_GTests_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TKG3d_GTests_FILES
  Geom_BezierCurve_Test.cxx
  Geom_BezierSurface_Test.cxx
  Geom_BSplineCurve_Test.cxx
  Geom_BSplineSurface_Test.cxx
  Geom_Circle_Test.cxx
  Geom_CurveEval_Test.cxx
  Geom_Line_Test.cxx
  Geom_OffsetCurve_Test.cxx
  Geom_OffsetSurface_Test.cxx
  Geom_Plane_Test.cxx
  Geom_SurfaceEval_Test.cxx
  GeomAdaptor_Curve_Test.cxx
  GeomEval_AHTBezierCurve_Test.cxx
  GeomEval_AHTBezierSurface_Test.cxx
  GeomEval_CircularHelicoidSurface_Test.cxx
  GeomEval_CircularHelixCurve_Test.cxx
  GeomEval_EllipsoidSurface_Test.cxx
  GeomEval_GregorySurface_Test.cxx
  GeomEval_HypParaboloidSurface_Test.cxx
  GeomEval_HyperboloidSurface_Test.cxx
  GeomEval_ParaboloidSurface_Test.cxx
  GeomEval_SineWaveCurve_Test.cxx
  GeomEval_TBezierCurve_Test.cxx
  GeomEval_TBezierSurface_Test.cxx
  GeomAPI_ExtremaCurveCurve_Test.cxx
  GeomAPI_Interpolate_Test.cxx
  GeomGridEval_BezierCurve_Test.cxx
  GeomGridEval_BezierSurface_Test.cxx
  GeomGridEval_BSplineSurface_Test.cxx
  GeomGridEval_Cone_Test.cxx
  GeomGridEval_Curve_Test.cxx
  GeomGridEval_Cylinder_Test.cxx
  GeomGridEval_Ellipse_Test.cxx
  GeomGridEval_Hyperbola_Test.cxx
  GeomGridEval_OffsetSurface_Test.cxx
  GeomGridEval_Parabola_Test.cxx
  GeomGridEval_Sphere_Test.cxx
  GeomGridEval_Surface_Test.cxx
  GeomGridEval_SurfaceOfExtrusion_Test.cxx
  GeomGridEval_SurfaceOfRevolution_Test.cxx
  GeomGridEval_Torus_Test.cxx
  GeomHash_CurveHasher_Test.cxx
  GeomHash_SurfaceHasher_Test.cxx
)
