

#ifndef QANCollection_DoubleMapIteratorOfDoubleMapOfRealInteger_HeaderFile
#define QANCollection_DoubleMapIteratorOfDoubleMapOfRealInteger_HeaderFile

#include <QANCollection_DoubleMapOfRealInteger.hxx>

#endif
