#include <StepShape_GeometricallyBoundedWireframeShapeRepresentation.ixx>


StepShape_GeometricallyBoundedWireframeShapeRepresentation::StepShape_GeometricallyBoundedWireframeShapeRepresentation ()  {}

