# Source files for Extrema package
set(OCCT_Extrema_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_Extrema_FILES
  Extrema_Array1OfPOnCurv.hxx
  Extrema_Array1OfPOnCurv2d.hxx
  Extrema_Array1OfPOnSurf.hxx
  Extrema_Array2OfPOnCurv.hxx
  Extrema_Array2OfPOnCurv2d.hxx
  Extrema_Array2OfPOnSurf.hxx
  Extrema_Array2OfPOnSurfParams.hxx
  Extrema_CCLocFOfLocECC.hxx
  Extrema_CCLocFOfLocECC2d.hxx
  Extrema_Curve2dTool.cxx
  Extrema_Curve2dTool.hxx
  Extrema_CurveTool.cxx
  Extrema_CurveTool.hxx
  Extrema_ECC.hxx
  Extrema_ECC2d.hxx
  Extrema_ElementType.hxx
  Extrema_ELPCOfLocateExtPC.hxx
  Extrema_ELPCOfLocateExtPC2d.hxx
  Extrema_EPCOfELPCOfLocateExtPC.hxx
  Extrema_EPCOfELPCOfLocateExtPC2d.hxx
  Extrema_EPCOfExtPC.hxx
  Extrema_EPCOfExtPC2d.hxx
  Extrema_ExtAlgo.hxx
  Extrema_ExtCC.cxx
  Extrema_ExtCC.hxx
  Extrema_ExtCC2d.cxx
  Extrema_ExtCC2d.hxx
  Extrema_ExtCS.cxx
  Extrema_ExtCS.hxx
  Extrema_ExtElC.cxx
  Extrema_ExtElC.hxx
  Extrema_ExtElC2d.cxx
  Extrema_ExtElC2d.hxx
  Extrema_ExtElCS.cxx
  Extrema_ExtElCS.hxx
  Extrema_ExtElSS.cxx
  Extrema_ExtElSS.hxx
  Extrema_ExtFlag.hxx
  Extrema_ExtPC.hxx
  Extrema_ExtPC2d.hxx
  Extrema_ExtPElC.cxx
  Extrema_ExtPElC.hxx
  Extrema_ExtPElC2d.cxx
  Extrema_ExtPElC2d.hxx
  Extrema_ExtPElS.cxx
  Extrema_ExtPElS.hxx
  Extrema_ExtPExtS.cxx
  Extrema_ExtPExtS.hxx
  Extrema_ExtPRevS.cxx
  Extrema_ExtPRevS.hxx
  Extrema_ExtPS.cxx
  Extrema_ExtPS.hxx
  Extrema_ExtSS.cxx
  Extrema_ExtSS.hxx
  Extrema_FuncExtCS.cxx
  Extrema_FuncExtCS.hxx
  Extrema_GFuncExtCC.hxx
  Extrema_GFuncExtPC.hxx
  Extrema_FuncPSNorm.cxx
  Extrema_FuncPSNorm.hxx
  Extrema_FuncPSDist.cxx
  Extrema_FuncPSDist.hxx
  Extrema_FuncExtSS.cxx
  Extrema_FuncExtSS.hxx
  Extrema_GCurveLocator.hxx
  Extrema_GGenExtCC.hxx
  Extrema_GenExtCS.cxx
  Extrema_GenExtCS.hxx
  Extrema_GGenExtPC.hxx
  Extrema_GenExtPS.cxx
  Extrema_GenExtPS.hxx
  Extrema_GenExtSS.cxx
  Extrema_GenExtSS.hxx
  Extrema_GenLocateExtCC.hxx
  Extrema_GenLocateExtCS.cxx
  Extrema_GenLocateExtCS.hxx
  Extrema_GenLocateExtPC.hxx
  Extrema_GenLocateExtPS.cxx
  Extrema_GenLocateExtPS.hxx
  Extrema_GenLocateExtSS.cxx
  Extrema_GenLocateExtSS.hxx
  Extrema_GGExtPC.hxx
  Extrema_GlobOptFuncCC.cxx
  Extrema_GlobOptFuncCC.hxx
  Extrema_GlobOptFuncCS.cxx
  Extrema_GlobOptFuncCS.hxx
  Extrema_GlobOptFuncConicS.cxx
  Extrema_GlobOptFuncConicS.hxx
  Extrema_GlobOptFuncCQuadric.cxx
  Extrema_GlobOptFuncCQuadric.hxx
  Extrema_GLocateExtPC.hxx
  Extrema_HArray1OfPOnCurv.hxx
  Extrema_HArray1OfPOnCurv2d.hxx
  Extrema_HArray1OfPOnSurf.hxx
  Extrema_HArray2OfPOnCurv.hxx
  Extrema_HArray2OfPOnCurv2d.hxx
  Extrema_HArray2OfPOnSurf.hxx
  Extrema_HUBTreeOfSphere.hxx
  Extrema_LocateExtCC.cxx
  Extrema_LocateExtCC.hxx
  Extrema_LocateExtCC2d.cxx
  Extrema_LocateExtCC2d.hxx
  Extrema_LocateExtPC.hxx
  Extrema_LocateExtPC2d.hxx
  Extrema_LocECC.hxx
  Extrema_LocECC2d.hxx
  Extrema_LocEPCOfLocateExtPC.hxx
  Extrema_LocEPCOfLocateExtPC2d.hxx
  Extrema_PCFOfEPCOfELPCOfLocateExtPC.hxx
  Extrema_PCFOfEPCOfELPCOfLocateExtPC2d.hxx
  Extrema_PCFOfEPCOfExtPC.hxx
  Extrema_PCFOfEPCOfExtPC2d.hxx
  Extrema_PCLocFOfLocEPCOfLocateExtPC.hxx
  Extrema_PCLocFOfLocEPCOfLocateExtPC2d.hxx
  Extrema_POnCurv.hxx
  Extrema_POnCurv2d.hxx
  Extrema_POnSurf.hxx
  Extrema_POnSurfParams.hxx
  Extrema_SequenceOfPOnCurv.hxx
  Extrema_SequenceOfPOnCurv2d.hxx
  Extrema_SequenceOfPOnSurf.hxx
)
