name: 'Download vcpkg Cache'
description: 'Download and restore vcpkg installed packages and cache'

inputs:
  artifact-name:
    description: 'Name of the artifact containing vcpkg cache'
    required: true
  build-directory:
    description: 'Build directory where vcpkg_installed should be restored'
    required: false
    default: 'build'

runs:
  using: "composite"
  steps:

    - name: Download vcpkg cache
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.build-directory }}/vcpkg_installed
