

#ifndef Resource_DataMapIteratorOfDataMapOfAsciiStringAsciiString_HeaderFile
#define Resource_DataMapIteratorOfDataMapOfAsciiStringAsciiString_HeaderFile

#include <Resource_DataMapOfAsciiStringAsciiString.hxx>

#endif
