

#ifndef Resource_DataMapIteratorOfDataMapOfAsciiStringExtendedString_HeaderFile
#define Resource_DataMapIteratorOfDataMapOfAsciiStringExtendedString_HeaderFile

#include <Resource_DataMapOfAsciiStringExtendedString.hxx>

#endif
