# Source files for RWStepShape package
set(OCCT_RWStepShape_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_RWStepShape_FILES
  RWStepShape_RWAdvancedBrepShapeRepresentation.cxx
  RWStepShape_RWAdvancedBrepShapeRepresentation.pxx
  RWStepShape_RWAdvancedFace.cxx
  RWStepShape_RWAdvancedFace.pxx
  RWStepShape_RWAngularLocation.cxx
  RWStepShape_RWAngularLocation.pxx
  RWStepShape_RWAngularSize.cxx
  RWStepShape_RWAngularSize.pxx
  RWStepShape_RWBlock.cxx
  RWStepShape_RWBlock.pxx
  RWStepShape_RWBooleanOperator.pxx
  RWStepShape_RWBooleanResult.cxx
  RWStepShape_RWBooleanResult.pxx
  RWStepShape_RWBoxDomain.cxx
  RWStepShape_RWBoxDomain.pxx
  RWStepShape_RWBoxedHalfSpace.cxx
  RWStepShape_RWBoxedHalfSpace.pxx
  RWStepShape_RWBrepWithVoids.cxx
  RWStepShape_RWBrepWithVoids.pxx
  RWStepShape_RWClosedShell.cxx
  RWStepShape_RWClosedShell.pxx
  RWStepShape_RWCompoundShapeRepresentation.cxx
  RWStepShape_RWCompoundShapeRepresentation.pxx
  RWStepShape_RWConnectedEdgeSet.cxx
  RWStepShape_RWConnectedEdgeSet.pxx
  RWStepShape_RWConnectedFaceSet.cxx
  RWStepShape_RWConnectedFaceSet.pxx
  RWStepShape_RWConnectedFaceShapeRepresentation.cxx
  RWStepShape_RWConnectedFaceShapeRepresentation.pxx
  RWStepShape_RWConnectedFaceSubSet.cxx
  RWStepShape_RWConnectedFaceSubSet.pxx
  RWStepShape_RWContextDependentShapeRepresentation.cxx
  RWStepShape_RWContextDependentShapeRepresentation.pxx
  RWStepShape_RWCsgShapeRepresentation.cxx
  RWStepShape_RWCsgShapeRepresentation.pxx
  RWStepShape_RWCsgSolid.cxx
  RWStepShape_RWCsgSolid.pxx
  RWStepShape_RWDefinitionalRepresentationAndShapeRepresentation.cxx
  RWStepShape_RWDefinitionalRepresentationAndShapeRepresentation.pxx
  RWStepShape_RWDimensionalCharacteristicRepresentation.cxx
  RWStepShape_RWDimensionalCharacteristicRepresentation.pxx
  RWStepShape_RWDimensionalLocation.cxx
  RWStepShape_RWDimensionalLocation.pxx
  RWStepShape_RWDimensionalLocationWithPath.cxx
  RWStepShape_RWDimensionalLocationWithPath.pxx
  RWStepShape_RWDimensionalSize.cxx
  RWStepShape_RWDimensionalSize.pxx
  RWStepShape_RWDimensionalSizeWithPath.cxx
  RWStepShape_RWDimensionalSizeWithPath.pxx
  RWStepShape_RWEdge.cxx
  RWStepShape_RWEdge.pxx
  RWStepShape_RWEdgeBasedWireframeModel.cxx
  RWStepShape_RWEdgeBasedWireframeModel.pxx
  RWStepShape_RWEdgeBasedWireframeShapeRepresentation.cxx
  RWStepShape_RWEdgeBasedWireframeShapeRepresentation.pxx
  RWStepShape_RWEdgeCurve.cxx
  RWStepShape_RWEdgeCurve.pxx
  RWStepShape_RWEdgeLoop.cxx
  RWStepShape_RWEdgeLoop.pxx
  RWStepShape_RWExtrudedAreaSolid.cxx
  RWStepShape_RWExtrudedAreaSolid.pxx
  RWStepShape_RWExtrudedFaceSolid.cxx
  RWStepShape_RWExtrudedFaceSolid.pxx
  RWStepShape_RWFace.cxx
  RWStepShape_RWFace.pxx
  RWStepShape_RWFaceBasedSurfaceModel.cxx
  RWStepShape_RWFaceBasedSurfaceModel.pxx
  RWStepShape_RWFaceBound.cxx
  RWStepShape_RWFaceBound.pxx
  RWStepShape_RWFaceOuterBound.cxx
  RWStepShape_RWFaceOuterBound.pxx
  RWStepShape_RWFaceSurface.cxx
  RWStepShape_RWFaceSurface.pxx
  RWStepShape_RWFacetedBrep.cxx
  RWStepShape_RWFacetedBrep.pxx
  RWStepShape_RWFacetedBrepAndBrepWithVoids.cxx
  RWStepShape_RWFacetedBrepAndBrepWithVoids.pxx
  RWStepShape_RWFacetedBrepShapeRepresentation.cxx
  RWStepShape_RWFacetedBrepShapeRepresentation.pxx
  RWStepShape_RWGeometricallyBoundedSurfaceShapeRepresentation.cxx
  RWStepShape_RWGeometricallyBoundedSurfaceShapeRepresentation.pxx
  RWStepShape_RWGeometricallyBoundedWireframeShapeRepresentation.cxx
  RWStepShape_RWGeometricallyBoundedWireframeShapeRepresentation.pxx
  RWStepShape_RWGeometricCurveSet.cxx
  RWStepShape_RWGeometricCurveSet.pxx
  RWStepShape_RWGeometricSet.cxx
  RWStepShape_RWGeometricSet.pxx
  RWStepShape_RWHalfSpaceSolid.cxx
  RWStepShape_RWHalfSpaceSolid.pxx
  RWStepShape_RWLimitsAndFits.cxx
  RWStepShape_RWLimitsAndFits.pxx
  RWStepShape_RWLoop.cxx
  RWStepShape_RWLoop.pxx
  RWStepShape_RWLoopAndPath.cxx
  RWStepShape_RWLoopAndPath.pxx
  RWStepShape_RWManifoldSolidBrep.cxx
  RWStepShape_RWManifoldSolidBrep.pxx
  RWStepShape_RWManifoldSurfaceShapeRepresentation.cxx
  RWStepShape_RWManifoldSurfaceShapeRepresentation.pxx
  RWStepShape_RWMeasureQualification.cxx
  RWStepShape_RWMeasureQualification.pxx
  RWStepShape_RWMeasureRepresentationItemAndQualifiedRepresentationItem.cxx
  RWStepShape_RWMeasureRepresentationItemAndQualifiedRepresentationItem.pxx
  RWStepShape_RWNonManifoldSurfaceShapeRepresentation.cxx
  RWStepShape_RWNonManifoldSurfaceShapeRepresentation.pxx
  RWStepShape_RWOpenShell.cxx
  RWStepShape_RWOpenShell.pxx
  RWStepShape_RWOrientedClosedShell.cxx
  RWStepShape_RWOrientedClosedShell.pxx
  RWStepShape_RWOrientedEdge.cxx
  RWStepShape_RWOrientedEdge.pxx
  RWStepShape_RWOrientedFace.cxx
  RWStepShape_RWOrientedFace.pxx
  RWStepShape_RWOrientedOpenShell.cxx
  RWStepShape_RWOrientedOpenShell.pxx
  RWStepShape_RWOrientedPath.cxx
  RWStepShape_RWOrientedPath.pxx
  RWStepShape_RWPath.cxx
  RWStepShape_RWPath.pxx
  RWStepShape_RWPlusMinusTolerance.cxx
  RWStepShape_RWPlusMinusTolerance.pxx
  RWStepShape_RWPointRepresentation.cxx
  RWStepShape_RWPointRepresentation.pxx
  RWStepShape_RWPolyLoop.cxx
  RWStepShape_RWPolyLoop.pxx
  RWStepShape_RWPrecisionQualifier.cxx
  RWStepShape_RWPrecisionQualifier.pxx
  RWStepShape_RWQualifiedRepresentationItem.cxx
  RWStepShape_RWQualifiedRepresentationItem.pxx
  RWStepShape_RWRevolvedAreaSolid.cxx
  RWStepShape_RWRevolvedAreaSolid.pxx
  RWStepShape_RWRevolvedFaceSolid.cxx
  RWStepShape_RWRevolvedFaceSolid.pxx
  RWStepShape_RWRightAngularWedge.cxx
  RWStepShape_RWRightAngularWedge.pxx
  RWStepShape_RWRightCircularCone.cxx
  RWStepShape_RWRightCircularCone.pxx
  RWStepShape_RWRightCircularCylinder.cxx
  RWStepShape_RWRightCircularCylinder.pxx
  RWStepShape_RWSeamEdge.cxx
  RWStepShape_RWSeamEdge.pxx
  RWStepShape_RWShapeDefinitionRepresentation.cxx
  RWStepShape_RWShapeDefinitionRepresentation.pxx
  RWStepShape_RWShapeDimensionRepresentation.cxx
  RWStepShape_RWShapeDimensionRepresentation.pxx
  RWStepShape_RWShapeRepresentation.cxx
  RWStepShape_RWShapeRepresentation.pxx
  RWStepShape_RWShapeRepresentationWithParameters.cxx
  RWStepShape_RWShapeRepresentationWithParameters.pxx
  RWStepShape_RWShellBasedSurfaceModel.cxx
  RWStepShape_RWShellBasedSurfaceModel.pxx
  RWStepShape_RWSolidModel.cxx
  RWStepShape_RWSolidModel.pxx
  RWStepShape_RWSolidReplica.cxx
  RWStepShape_RWSolidReplica.pxx
  RWStepShape_RWSphere.cxx
  RWStepShape_RWSphere.pxx
  RWStepShape_RWSubedge.cxx
  RWStepShape_RWSubedge.pxx
  RWStepShape_RWSubface.cxx
  RWStepShape_RWSubface.pxx
  RWStepShape_RWSweptAreaSolid.cxx
  RWStepShape_RWSweptAreaSolid.pxx
  RWStepShape_RWSweptFaceSolid.cxx
  RWStepShape_RWSweptFaceSolid.pxx
  RWStepShape_RWToleranceValue.cxx
  RWStepShape_RWToleranceValue.pxx
  RWStepShape_RWTopologicalRepresentationItem.cxx
  RWStepShape_RWTopologicalRepresentationItem.pxx
  RWStepShape_RWTorus.cxx
  RWStepShape_RWTorus.pxx
  RWStepShape_RWTransitionalShapeRepresentation.cxx
  RWStepShape_RWTransitionalShapeRepresentation.pxx
  RWStepShape_RWTypeQualifier.cxx
  RWStepShape_RWTypeQualifier.pxx
  RWStepShape_RWValueFormatTypeQualifier.cxx
  RWStepShape_RWValueFormatTypeQualifier.pxx
  RWStepShape_RWVertex.cxx
  RWStepShape_RWVertex.pxx
  RWStepShape_RWVertexLoop.cxx
  RWStepShape_RWVertexLoop.pxx
  RWStepShape_RWVertexPoint.cxx
  RWStepShape_RWVertexPoint.pxx
)
