name: Build Documentation
description: 'Build OCCT documentation using doxygen'

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        choco install -y graphviz
        choco install -y doxygen.install
      shell: pwsh

    - name: Configure OCCT
      run: |
          mkdir build
          cd build
          cmake -T host=x64 `
                -D BUILD_USE_PCH=ON `
                -D BUILD_OPT_PROFILE=Production `
                -D BUILD_INCLUDE_SYMLINK=ON `
                -D CMAKE_BUILD_TYPE=Release `
                -D BUILD_DOC_Overview=ON `
                -D BUILD_DOC_RefMan=ON `
                -D BUILD_MODULE_Draw=OFF `
                -D USE_D3D=OFF `
                -D USE_DRACO=OFF `
                -D USE_FFMPEG=OFF `
                -D USE_FREEIMAGE=OFF `
                -D USE_GLES2=OFF `
                -D USE_OPENVR=OFF `
                -D USE_VTK=OFF `
                -D USE_TBB=OFF `
                -D USE_RAPIDJSON=OFF `
                -D USE_OPENGL=OFF `
                -D USE_FREETYPE=OFF `
                -D USE_TK=OFF `
                -D USE_TCL=OFF `
                -D CMAKE_CXX_FLAGS="/W4 /WX" `
                -D CMAKE_C_FLAGS="/W4 /WX" ..
      shell: pwsh

    - name: Build documentation
      run: |
          set PATH=%PATH%;C:\Program Files\doxygen\bin;C:\Program Files\Graphviz\bin;C:\Program Files\doxygen
          cd build
          cmake --build . --target doc --config Release & exit /b 0
      shell: cmd

    - name: Upload refman documentation
      uses: actions/upload-artifact@v4.6.2
      with:
        name: refman-doc
        path: build/doc/refman
        retention-days: 90

    - name: Upload overview documentation
      uses: actions/upload-artifact@v4.6.2
      with:
        name: overview-doc
        path: build/doc/overview
        retention-days: 90
