

#ifndef TopOpeBRepDS_DataMapIteratorOfDataMapOfIntegerListOfInterference_HeaderFile
#define TopOpeBRepDS_DataMapIteratorOfDataMapOfIntegerListOfInterference_HeaderFile

#include <TopOpeBRepDS_DataMapOfIntegerListOfInterference.hxx>

#endif
