

#ifndef TopOpeBRepDS_DoubleMapIteratorOfDoubleMapOfIntegerShape_HeaderFile
#define TopOpeBRepDS_DoubleMapIteratorOfDoubleMapOfIntegerShape_HeaderFile

#include <TopOpeBRepDS_DoubleMapOfIntegerShape.hxx>

#endif
