#ifndef __INCLUDE_LIBRARY_BUF_CMD_RSP_SIZ_H
# define __INCLUDE_LIBRARY_BUF_CMD_RSP_SIZ_H

#ifdef CSF1
#define BUF_CMD_SIZ_WRD 1000
#define BUF_RSP_SIZ_WRD 1000

#else
#define BUF_CMD_SIZ_WRD 640
#define BUF_RSP_SIZ_WRD 640
#endif

#define BUF_CMD_SIZ_BYT BUF_CMD_SIZ_WRD*4
#define BUF_RSP_SIZ_BYT BUF_RSP_SIZ_WRD*4

#endif  /* __INCLUDE_LIBRARY_BUF_CMD_RSP_SIZ_H */
