

#ifndef BRepOffset_DataMapIteratorOfDataMapOfShapeMapOfShape_HeaderFile
#define BRepOffset_DataMapIteratorOfDataMapOfShapeMapOfShape_HeaderFile

#include <BRepOffset_DataMapOfShapeMapOfShape.hxx>

#endif
