# Test source files for TKernel
set(OCCT_TKernel_GTests_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TKernel_GTests_FILES
  Handle_Advanced_Test.cxx
  Handle_Operations_Test.cxx
  Message_Messenger_Test.cxx
  NCollection_Array1_Test.cxx
  NCollection_Array2_Test.cxx
  NCollection_BaseAllocator_Test.cxx
  NCollection_DataMap_Test.cxx
  NCollection_DoubleMap_Test.cxx
  NCollection_IndexedDataMap_Test.cxx
  NCollection_IndexedMap_Test.cxx
  NCollection_List_Test.cxx
  NCollection_LocalArray_Test.cxx
  NCollection_Map_Test.cxx
  NCollection_OccAllocator_Test.cxx
  NCollection_Sequence_Test.cxx
  NCollection_SparseArray_Test.cxx
  NCollection_Vec4_Test.cxx
  NCollection_Vector_Test.cxx
  OSD_Path_Test.cxx
  OSD_PerfMeter_Test.cxx
  Quantity_Color_Test.cxx
  Quantity_ColorRGBA_Test.cxx
  Quantity_Date_Test.cxx
  Quantity_Period_Test.cxx
  Standard_ArrayStreamBuffer_Test.cxx
  Standard_Atomic_Test.cxx
  Standard_Character_Test.cxx
  Standard_Dump_Test.cxx
  Standard_Failure_Test.cxx
  Standard_GUID_Test.cxx
  Standard_Handle_Test.cxx
  TCollection_AsciiString_Test.cxx
  TCollection_ExtendedString_Test.cxx
  TopLoc_Location_Test.cxx
  UnitsAPI_Test.cxx
)
