

#ifndef TColStd_DataMapIteratorOfDataMapOfTransientTransient_HeaderFile
#define TColStd_DataMapIteratorOfDataMapOfTransientTransient_HeaderFile

#include <TColStd_DataMapOfTransientTransient.hxx>

#endif
