

#ifndef TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger_HeaderFile
#define TColStd_DataMapIteratorOfDataMapOfIntegerListOfInteger_HeaderFile

#include <TColStd_DataMapOfIntegerListOfInteger.hxx>

#endif
