

#ifndef STEPCAFControl_DataMapIteratorOfDataMapOfLabelExternFile_HeaderFile
#define STEPCAFControl_DataMapIteratorOfDataMapOfLabelExternFile_HeaderFile

#include <STEPCAFControl_DataMapOfLabelExternFile.hxx>

#endif
