

#ifndef STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile_HeaderFile
#define STEPCAFControl_DataMapIteratorOfDataMapOfSDRExternFile_HeaderFile

#include <STEPCAFControl_DataMapOfSDRExternFile.hxx>

#endif
