

#ifndef STEPCAFControl_DataMapIteratorOfDataMapOfPDExternFile_HeaderFile
#define STEPCAFControl_DataMapIteratorOfDataMapOfPDExternFile_HeaderFile

#include <STEPCAFControl_DataMapOfPDExternFile.hxx>

#endif
