

#ifndef TNaming_DataMapIteratorOfDataMapOfShapePtrRefShape_HeaderFile
#define TNaming_DataMapIteratorOfDataMapOfShapePtrRefShape_HeaderFile

#include <TNaming_DataMapOfShapePtrRefShape.hxx>

#endif
