# Source files for RWStepGeom package
set(OCCT_RWStepGeom_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_RWStepGeom_FILES
  RWStepGeom_RWAxis1Placement.cxx
  RWStepGeom_RWAxis1Placement.pxx
  RWStepGeom_RWAxis2Placement2d.cxx
  RWStepGeom_RWAxis2Placement2d.pxx
  RWStepGeom_RWAxis2Placement3d.cxx
  RWStepGeom_RWAxis2Placement3d.pxx
  RWStepGeom_RWBezierCurve.cxx
  RWStepGeom_RWBezierCurve.pxx
  RWStepGeom_RWBezierCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWBezierCurveAndRationalBSplineCurve.pxx
  RWStepGeom_RWBezierSurface.cxx
  RWStepGeom_RWBezierSurface.pxx
  RWStepGeom_RWBezierSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWBezierSurfaceAndRationalBSplineSurface.pxx
  RWStepGeom_RWBoundaryCurve.cxx
  RWStepGeom_RWBoundaryCurve.pxx
  RWStepGeom_RWBoundedCurve.cxx
  RWStepGeom_RWBoundedCurve.pxx
  RWStepGeom_RWBoundedSurface.cxx
  RWStepGeom_RWBoundedSurface.pxx
  RWStepGeom_RWBSplineCurve.cxx
  RWStepGeom_RWBSplineCurve.pxx
  RWStepGeom_RWBSplineCurveWithKnots.cxx
  RWStepGeom_RWBSplineCurveForm.pxx
  RWStepGeom_RWBSplineCurveWithKnots.pxx
  RWStepGeom_RWBSplineCurveWithKnotsAndRationalBSplineCurve.cxx
  RWStepGeom_RWBSplineCurveWithKnotsAndRationalBSplineCurve.pxx
  RWStepGeom_RWBSplineSurface.cxx
  RWStepGeom_RWBSplineSurface.pxx
  RWStepGeom_RWBSplineSurfaceWithKnots.cxx
  RWStepGeom_RWBSplineSurfaceForm.pxx
  RWStepGeom_RWBSplineSurfaceWithKnots.pxx
  RWStepGeom_RWBSplineSurfaceWithKnotsAndRationalBSplineSurface.cxx
  RWStepGeom_RWBSplineSurfaceWithKnotsAndRationalBSplineSurface.pxx
  RWStepGeom_RWCartesianPoint.cxx
  RWStepGeom_RWCartesianPoint.pxx
  RWStepGeom_RWCartesianTransformationOperator.cxx
  RWStepGeom_RWCartesianTransformationOperator.pxx
  RWStepGeom_RWCartesianTransformationOperator3d.cxx
  RWStepGeom_RWCartesianTransformationOperator3d.pxx
  RWStepGeom_RWCircle.cxx
  RWStepGeom_RWCircle.pxx
  RWStepGeom_RWCompositeCurve.cxx
  RWStepGeom_RWCompositeCurve.pxx
  RWStepGeom_RWCompositeCurveOnSurface.cxx
  RWStepGeom_RWCompositeCurveOnSurface.pxx
  RWStepGeom_RWCompositeCurveSegment.cxx
  RWStepGeom_RWCompositeCurveSegment.pxx
  RWStepGeom_RWConic.cxx
  RWStepGeom_RWConic.pxx
  RWStepGeom_RWConicalSurface.cxx
  RWStepGeom_RWConicalSurface.pxx
  RWStepGeom_RWCurve.cxx
  RWStepGeom_RWCurve.pxx
  RWStepGeom_RWCurveBoundedSurface.cxx
  RWStepGeom_RWCurveBoundedSurface.pxx
  RWStepGeom_RWCurveReplica.cxx
  RWStepGeom_RWCurveReplica.pxx
  RWStepGeom_RWCylindricalSurface.cxx
  RWStepGeom_RWCylindricalSurface.pxx
  RWStepGeom_RWDegeneratePcurve.cxx
  RWStepGeom_RWDegeneratePcurve.pxx
  RWStepGeom_RWDegenerateToroidalSurface.cxx
  RWStepGeom_RWDegenerateToroidalSurface.pxx
  RWStepGeom_RWDirection.cxx
  RWStepGeom_RWDirection.pxx
  RWStepGeom_RWElementarySurface.cxx
  RWStepGeom_RWElementarySurface.pxx
  RWStepGeom_RWEllipse.cxx
  RWStepGeom_RWEllipse.pxx
  RWStepGeom_RWEvaluatedDegeneratePcurve.cxx
  RWStepGeom_RWEvaluatedDegeneratePcurve.pxx
  RWStepGeom_RWGeometricRepresentationContext.cxx
  RWStepGeom_RWGeometricRepresentationContext.pxx
  RWStepGeom_RWGeometricRepresentationContextAndGlobalUnitAssignedContext.cxx
  RWStepGeom_RWGeometricRepresentationContextAndGlobalUnitAssignedContext.pxx
  RWStepGeom_RWGeometricRepresentationContextAndParametricRepresentationContext.cxx
  RWStepGeom_RWGeometricRepresentationContextAndParametricRepresentationContext.pxx
  RWStepGeom_RWGeometricRepresentationItem.cxx
  RWStepGeom_RWGeometricRepresentationItem.pxx
  RWStepGeom_RWGeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.cxx
  RWStepGeom_RWGeomRepContextAndGlobUnitAssCtxAndGlobUncertaintyAssCtx.pxx
  RWStepGeom_RWHyperbola.cxx
  RWStepGeom_RWHyperbola.pxx
  RWStepGeom_RWIntersectionCurve.cxx
  RWStepGeom_RWIntersectionCurve.pxx
  RWStepGeom_RWKnotType.pxx
  RWStepGeom_RWLine.cxx
  RWStepGeom_RWLine.pxx
  RWStepGeom_RWOffsetCurve3d.cxx
  RWStepGeom_RWOffsetCurve3d.pxx
  RWStepGeom_RWOffsetSurface.cxx
  RWStepGeom_RWOffsetSurface.pxx
  RWStepGeom_RWOrientedSurface.cxx
  RWStepGeom_RWOrientedSurface.pxx
  RWStepGeom_RWOuterBoundaryCurve.cxx
  RWStepGeom_RWOuterBoundaryCurve.pxx
  RWStepGeom_RWParabola.cxx
  RWStepGeom_RWParabola.pxx
  RWStepGeom_RWPcurve.cxx
  RWStepGeom_RWPcurve.pxx
  RWStepGeom_RWPlacement.cxx
  RWStepGeom_RWPlacement.pxx
  RWStepGeom_RWPlane.cxx
  RWStepGeom_RWPlane.pxx
  RWStepGeom_RWPoint.cxx
  RWStepGeom_RWPoint.pxx
  RWStepGeom_RWPointOnCurve.cxx
  RWStepGeom_RWPointOnCurve.pxx
  RWStepGeom_RWPointOnSurface.cxx
  RWStepGeom_RWPointOnSurface.pxx
  RWStepGeom_RWPointReplica.cxx
  RWStepGeom_RWPointReplica.pxx
  RWStepGeom_RWPolyline.cxx
  RWStepGeom_RWPolyline.pxx
  RWStepGeom_RWPreferredSurfaceCurveRepresentation.pxx
  RWStepGeom_RWQuasiUniformCurve.cxx
  RWStepGeom_RWQuasiUniformCurve.pxx
  RWStepGeom_RWQuasiUniformCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWQuasiUniformCurveAndRationalBSplineCurve.pxx
  RWStepGeom_RWQuasiUniformSurface.cxx
  RWStepGeom_RWQuasiUniformSurface.pxx
  RWStepGeom_RWQuasiUniformSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWQuasiUniformSurfaceAndRationalBSplineSurface.pxx
  RWStepGeom_RWRationalBSplineCurve.cxx
  RWStepGeom_RWRationalBSplineCurve.pxx
  RWStepGeom_RWRationalBSplineSurface.cxx
  RWStepGeom_RWRationalBSplineSurface.pxx
  RWStepGeom_RWRectangularCompositeSurface.cxx
  RWStepGeom_RWRectangularCompositeSurface.pxx
  RWStepGeom_RWRectangularTrimmedSurface.cxx
  RWStepGeom_RWRectangularTrimmedSurface.pxx
  RWStepGeom_RWReparametrisedCompositeCurveSegment.cxx
  RWStepGeom_RWReparametrisedCompositeCurveSegment.pxx
  RWStepGeom_RWSeamCurve.cxx
  RWStepGeom_RWSeamCurve.pxx
  RWStepGeom_RWSphericalSurface.cxx
  RWStepGeom_RWSphericalSurface.pxx
  RWStepGeom_RWSuParameters.cxx
  RWStepGeom_RWSuParameters.pxx
  RWStepGeom_RWSurface.cxx
  RWStepGeom_RWSurface.pxx
  RWStepGeom_RWSurfaceCurve.cxx
  RWStepGeom_RWSurfaceCurve.pxx
  RWStepGeom_RWSurfaceCurveAndBoundedCurve.cxx
  RWStepGeom_RWSurfaceCurveAndBoundedCurve.pxx
  RWStepGeom_RWSurfaceOfLinearExtrusion.cxx
  RWStepGeom_RWSurfaceOfLinearExtrusion.pxx
  RWStepGeom_RWSurfaceOfRevolution.cxx
  RWStepGeom_RWSurfaceOfRevolution.pxx
  RWStepGeom_RWSurfacePatch.cxx
  RWStepGeom_RWSurfacePatch.pxx
  RWStepGeom_RWSurfaceReplica.cxx
  RWStepGeom_RWSurfaceReplica.pxx
  RWStepGeom_RWSweptSurface.cxx
  RWStepGeom_RWSweptSurface.pxx
  RWStepGeom_RWToroidalSurface.cxx
  RWStepGeom_RWToroidalSurface.pxx
  RWStepGeom_RWTransitionCode.pxx
  RWStepGeom_RWTrimmedCurve.cxx
  RWStepGeom_RWTrimmedCurve.pxx
  RWStepGeom_RWUniformCurve.cxx
  RWStepGeom_RWUniformCurve.pxx
  RWStepGeom_RWUniformCurveAndRationalBSplineCurve.cxx
  RWStepGeom_RWUniformCurveAndRationalBSplineCurve.pxx
  RWStepGeom_RWUniformSurface.cxx
  RWStepGeom_RWUniformSurface.pxx
  RWStepGeom_RWUniformSurfaceAndRationalBSplineSurface.cxx
  RWStepGeom_RWUniformSurfaceAndRationalBSplineSurface.pxx
  RWStepGeom_RWVector.cxx
  RWStepGeom_RWVector.pxx
)
