/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fTypeOfVisualization */

#ifndef _Included_CASCADESamplesJni_V3d_0005fTypeOfVisualization
#define _Included_CASCADESamplesJni_V3d_0005fTypeOfVisualization
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_V3d_0005fTypeOfVisualization_V3d_WIREFRAME
#define CASCADESamplesJni_V3d_0005fTypeOfVisualization_V3d_WIREFRAME 0L
#undef CASCADESamplesJni_V3d_0005fTypeOfVisualization_V3d_ZBUFFER
#define CASCADESamplesJni_V3d_0005fTypeOfVisualization_V3d_ZBUFFER 1L
#ifdef __cplusplus
}
#endif
#endif
