/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Viewer_0005fView */

#ifndef _Included_CASCADESamplesJni_Viewer_0005fView
#define _Included_CASCADESamplesJni_Viewer_0005fView
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_Viewer_0005fView
 * Method:    Place
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Viewer_1View_Place
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     CASCADESamplesJni_Viewer_0005fView
 * Method:    SetImmediateUpdate
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_Viewer_1View_SetImmediateUpdate
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_Viewer_0005fView
 * Method:    Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Viewer_1View_Update
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Viewer_0005fView
 * Method:    WindowFit
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Viewer_1View_WindowFit
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
