/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fPerspectiveView */

#ifndef _Included_CASCADESamplesJni_V3d_0005fPerspectiveView
#define _Included_CASCADESamplesJni_V3d_0005fPerspectiveView
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    Angle
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_Angle
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    Copy
 * Signature: ()LCASCADESamplesJni/V3d_PerspectiveView;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_Copy
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    SetAngle
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_SetAngle
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    V3d_PerspectiveView_Create_1
 * Signature: (LCASCADESamplesJni/V3d_Viewer;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_V3d_1PerspectiveView_1Create_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    V3d_PerspectiveView_Create_2
 * Signature: (LCASCADESamplesJni/V3d_Viewer;LCASCADESamplesJni/V3d_OrthographicView;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_V3d_1PerspectiveView_1Create_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fPerspectiveView
 * Method:    V3d_PerspectiveView_Create_3
 * Signature: (LCASCADESamplesJni/V3d_Viewer;LCASCADESamplesJni/V3d_PerspectiveView;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1PerspectiveView_V3d_1PerspectiveView_1Create_13
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
