/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Aspect_0005fBackground */

#ifndef _Included_CASCADESamplesJni_Aspect_0005fBackground
#define _Included_CASCADESamplesJni_Aspect_0005fBackground
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_Aspect_0005fBackground
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1Background_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
