/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Prs3d_0005fLineAspect */

#ifndef _Included_CASCADESamplesJni_Prs3d_0005fLineAspect
#define _Included_CASCADESamplesJni_Prs3d_0005fLineAspect
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
