/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADEView2d */

#ifndef _Included_CASCADEView2d
#define _Included_CASCADEView2d
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: LOCK */
/* Inaccessible static: dbg */
/* Inaccessible static: isInc */
/* Inaccessible static: incRate */
#undef CASCADEView2d_TOP_ALIGNMENT
#define CASCADEView2d_TOP_ALIGNMENT 0.0f
#undef CASCADEView2d_CENTER_ALIGNMENT
#define CASCADEView2d_CENTER_ALIGNMENT 0.5f
#undef CASCADEView2d_BOTTOM_ALIGNMENT
#define CASCADEView2d_BOTTOM_ALIGNMENT 1.0f
#undef CASCADEView2d_LEFT_ALIGNMENT
#define CASCADEView2d_LEFT_ALIGNMENT 0.0f
#undef CASCADEView2d_RIGHT_ALIGNMENT
#define CASCADEView2d_RIGHT_ALIGNMENT 1.0f
#undef CASCADEView2d_serialVersionUID
#define CASCADEView2d_serialVersionUID -7644114512714619750LL
/* Inaccessible static: metrics */
/* Inaccessible static: class_00024java_00024awt_00024Component */
/* Inaccessible static: class_00024java_00024awt_00024event_00024ComponentListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024FocusListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024HierarchyBoundsListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024KeyListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024MouseMotionListener */
/* Inaccessible static: class_00024java_00024awt_00024event_00024InputMethodListener */
/* Inaccessible static: nameCounter */
#undef CASCADEView2d_serialVersionUID
#define CASCADEView2d_serialVersionUID -2284879212465893870LL
/* Inaccessible static: resGui */
/* Inaccessible static: AppRes */
#undef CASCADEView2d_NOTHING
#define CASCADEView2d_NOTHING 0L
#undef CASCADEView2d_WINDOWFIT
#define CASCADEView2d_WINDOWFIT 1L
#undef CASCADEView2d_ZOOMVIEW
#define CASCADEView2d_ZOOMVIEW 2L
#undef CASCADEView2d_PANVIEW
#define CASCADEView2d_PANVIEW 3L
#undef CASCADEView2d_MAGNIFY
#define CASCADEView2d_MAGNIFY 4L
#undef CASCADEView2d_PANGLOBAL
#define CASCADEView2d_PANGLOBAL 5L
#undef CASCADEView2d_ROTATE
#define CASCADEView2d_ROTATE 6L
/* Inaccessible static: defCursor */
/* Inaccessible static: handCursor */
#undef CASCADEView2d_OS_UNKNOWN
#define CASCADEView2d_OS_UNKNOWN 0L
#undef CASCADEView2d_OS_WINDOWS
#define CASCADEView2d_OS_WINDOWS 1L
#undef CASCADEView2d_OS_X11
#define CASCADEView2d_OS_X11 2L
/* Inaccessible static: osType */
/* Inaccessible static: theGraphicsConfiguration */

/*
 * Class:     CASCADEView2d
 * Method:    paint
 * Signature: (Ljava/awt/Graphics;)V
 */
JNIEXPORT void JNICALL Java_CASCADEView2d_paint
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
