/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_PrsMgr_0005fPresentationManager */

#ifndef _Included_CASCADESamplesJni_PrsMgr_0005fPresentationManager
#define _Included_CASCADESamplesJni_PrsMgr_0005fPresentationManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
