/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_TopoDS_0005fTShape */

#ifndef _Included_CASCADESamplesJni_TopoDS_0005fTShape
#define _Included_CASCADESamplesJni_TopoDS_0005fTShape
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
