/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_AIS_0005fTypeOfIso */

#ifndef _Included_CASCADESamplesJni_AIS_0005fTypeOfIso
#define _Included_CASCADESamplesJni_AIS_0005fTypeOfIso
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_IsoU
#define CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_IsoU 0L
#undef CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_IsoV
#define CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_IsoV 1L
#undef CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_Both
#define CASCADESamplesJni_AIS_0005fTypeOfIso_AIS_TOI_Both 2L
#ifdef __cplusplus
}
#endif
#endif
