/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_TColgp_0005fArray1OfPnt2d */

#ifndef _Included_CASCADESamplesJni_TColgp_0005fArray1OfPnt2d
#define _Included_CASCADESamplesJni_TColgp_0005fArray1OfPnt2d
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_TColgp_0005fArray1OfPnt2d
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TColgp_1Array1OfPnt2d_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
