/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail */

#ifndef _Included_CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail
#define _Included_CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_NONE
#define CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_NONE 0L
#undef CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_ENVIRONMENT
#define CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_ENVIRONMENT 1L
#undef CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_ALL
#define CASCADESamplesJni_V3d_0005fTypeOfSurfaceDetail_V3d_TEX_ALL 2L
#ifdef __cplusplus
}
#endif
#endif
