/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fOrthographicView */

#ifndef _Included_CASCADESamplesJni_V3d_0005fOrthographicView
#define _Included_CASCADESamplesJni_V3d_0005fOrthographicView
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_V3d_0005fOrthographicView
 * Method:    Copy
 * Signature: ()LCASCADESamplesJni/V3d_OrthographicView;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1OrthographicView_Copy
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fOrthographicView
 * Method:    V3d_OrthographicView_Create_1
 * Signature: (LCASCADESamplesJni/V3d_Viewer;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1OrthographicView_V3d_1OrthographicView_1Create_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fOrthographicView
 * Method:    V3d_OrthographicView_Create_2
 * Signature: (LCASCADESamplesJni/V3d_Viewer;LCASCADESamplesJni/V3d_PerspectiveView;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1OrthographicView_V3d_1OrthographicView_1Create_12
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fOrthographicView
 * Method:    V3d_OrthographicView_Create_3
 * Signature: (LCASCADESamplesJni/V3d_Viewer;LCASCADESamplesJni/V3d_OrthographicView;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1OrthographicView_V3d_1OrthographicView_1Create_13
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
