/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_TCollection_0005fAsciiString */

#ifndef _Included_CASCADESamplesJni_TCollection_0005fAsciiString
#define _Included_CASCADESamplesJni_TCollection_0005fAsciiString
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Capitalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Capitalize
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Center
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Center
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    ChangeAll
 * Signature: (Ljcas/Standard_Character;Ljcas/Standard_Character;Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_ChangeAll
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Clear
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    FirstLocationInSet
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;II)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_FirstLocationInSet
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    FirstLocationNotInSet
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;II)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_FirstLocationNotInSet
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    HASHCODE
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;I)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_HASHCODE
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    HashCode
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;I)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_HashCode
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    ISSIMILAR
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_ISSIMILAR
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    InsertAfter
 * Signature: (ILCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_InsertAfter
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    InsertBefore
 * Signature: (ILCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_InsertBefore
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    IntegerValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_IntegerValue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    IsAscii
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_IsAscii
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    IsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_IsEmpty
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    IsIntegerValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_IsIntegerValue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    IsRealValue
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_IsRealValue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    LeftAdjust
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_LeftAdjust
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    LeftJustify
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_LeftJustify
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Length
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    LowerCase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_LowerCase
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Prepend
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Prepend
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    RealValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_RealValue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Remove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Remove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    RightAdjust
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_RightAdjust
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    RightJustify
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_RightJustify
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_AssignCat_1
 * Signature: (Ljcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1AssignCat_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_AssignCat_2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1AssignCat_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_AssignCat_3
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1AssignCat_13
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_AssignCat_4
 * Signature: (Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1AssignCat_14
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_AssignCat_5
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1AssignCat_15
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Cat_1
 * Signature: (Ljcas/Standard_Character;)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Cat_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Cat_2
 * Signature: (I)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Cat_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Cat_3
 * Signature: (D)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Cat_13
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Cat_4
 * Signature: (Ljcas/Standard_CString;)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Cat_14
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Cat_5
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Cat_15
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Copy_1
 * Signature: (Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Copy_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Copy_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Copy_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_10
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_110
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_11
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;LCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_111
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_12
 * Signature: (LCASCADESamplesJni/TCollection_ExtendedString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_112
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_2
 * Signature: (Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_3
 * Signature: (Ljcas/Standard_CString;I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_13
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_4
 * Signature: (Ljcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_14
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_5
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_15
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_6
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_16
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_7
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_17
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_8
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_18
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Create_9
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;Ljcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Create_19
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Insert_1
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Insert_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Insert_2
 * Signature: (ILjcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Insert_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Insert_3
 * Signature: (ILCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Insert_13
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsDifferent_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsDifferent_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsDifferent_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsDifferent_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsEqual_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsEqual_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsEqual_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsEqual_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsEqual_3
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsEqual_13
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsEqual_4
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsEqual_14
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsGreater_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsGreater_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsGreater_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsGreater_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsLess_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsLess_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_IsLess_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1IsLess_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Location_1
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;II)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Location_11
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Location_2
 * Signature: (ILjcas/Standard_Character;II)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Location_12
  (JNIEnv *, jobject, jint, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_RemoveAll_1
 * Signature: (Ljcas/Standard_Character;Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1RemoveAll_11
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_RemoveAll_2
 * Signature: (Ljcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1RemoveAll_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SearchFromEnd_1
 * Signature: (Ljcas/Standard_CString;)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SearchFromEnd_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SearchFromEnd_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SearchFromEnd_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Search_1
 * Signature: (Ljcas/Standard_CString;)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Search_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Search_2
 * Signature: (LCASCADESamplesJni/TCollection_AsciiString;)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Search_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SetValue_1
 * Signature: (ILjcas/Standard_Character;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SetValue_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SetValue_2
 * Signature: (ILjcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SetValue_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SetValue_3
 * Signature: (ILCASCADESamplesJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SetValue_13
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Split_2
 * Signature: (I)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Split_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_SubString_2
 * Signature: (II)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1SubString_12
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    TCollection_AsciiString_Token_2
 * Signature: (Ljcas/Standard_CString;I)LCASCADESamplesJni/TCollection_AsciiString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_TCollection_1AsciiString_1Token_12
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    ToCString
 * Signature: ()Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_ToCString
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Trunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Trunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    UpperCase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_UpperCase
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    UsefullLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_UsefullLength
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_TCollection_0005fAsciiString
 * Method:    Value
 * Signature: (I)Ljcas/Standard_Character;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_TCollection_1AsciiString_Value
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
