/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fTypeOfAxe */

#ifndef _Included_CASCADESamplesJni_V3d_0005fTypeOfAxe
#define _Included_CASCADESamplesJni_V3d_0005fTypeOfAxe
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_X
#define CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_X 0L
#undef CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_Y
#define CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_Y 1L
#undef CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_Z
#define CASCADESamplesJni_V3d_0005fTypeOfAxe_V3d_Z 2L
#ifdef __cplusplus
}
#endif
#endif
