/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Aspect_0005fLineStyle */

#ifndef _Included_CASCADESamplesJni_Aspect_0005fLineStyle
#define _Included_CASCADESamplesJni_Aspect_0005fLineStyle
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Aspect_LineStyle_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Aspect_1LineStyle_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Aspect_LineStyle_Create_2
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Aspect_1LineStyle_1Create_12
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Aspect_LineStyle_Create_3
 * Signature: (LCASCADESamplesJni/TColQuantity_Array1OfLength;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Aspect_1LineStyle_1Create_13
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Aspect_LineStyle_SetValues_1
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Aspect_1LineStyle_1SetValues_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Aspect_LineStyle_SetValues_2
 * Signature: (LCASCADESamplesJni/TColQuantity_Array1OfLength;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Aspect_1LineStyle_1SetValues_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Assign
 * Signature: (LCASCADESamplesJni/Aspect_LineStyle;)LCASCADESamplesJni/Aspect_LineStyle;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    IsEqual
 * Signature: (LCASCADESamplesJni/Aspect_LineStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_IsEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    IsNotEqual
 * Signature: (LCASCADESamplesJni/Aspect_LineStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_IsNotEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Length
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Style
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Style
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Aspect_0005fLineStyle
 * Method:    Values
 * Signature: ()LCASCADESamplesJni/TColQuantity_Array1OfLength;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_Aspect_1LineStyle_Values
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
