/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_SelectMgr_0005fSelectionManager */

#ifndef _Included_CASCADESamplesJni_SelectMgr_0005fSelectionManager
#define _Included_CASCADESamplesJni_SelectMgr_0005fSelectionManager
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
