/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fTypeOfProjectionModel */

#ifndef _Included_CASCADESamplesJni_V3d_0005fTypeOfProjectionModel
#define _Included_CASCADESamplesJni_V3d_0005fTypeOfProjectionModel
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_V3d_0005fTypeOfProjectionModel_V3d_TPM_SCREEN
#define CASCADESamplesJni_V3d_0005fTypeOfProjectionModel_V3d_TPM_SCREEN 0L
#undef CASCADESamplesJni_V3d_0005fTypeOfProjectionModel_V3d_TPM_WALKTHROUGH
#define CASCADESamplesJni_V3d_0005fTypeOfProjectionModel_V3d_TPM_WALKTHROUGH 1L
#ifdef __cplusplus
}
#endif
#endif
