/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_SelectMgr_0005fSequenceOfOwner */

#ifndef _Included_CASCADESamplesJni_SelectMgr_0005fSequenceOfOwner
#define _Included_CASCADESamplesJni_SelectMgr_0005fSequenceOfOwner
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_SelectMgr_0005fSequenceOfOwner
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_SelectMgr_1SequenceOfOwner_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
