/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_TColStd_0005fListOfInteger */

#ifndef _Included_CASCADESamplesJni_TColStd_0005fListOfInteger
#define _Included_CASCADESamplesJni_TColStd_0005fListOfInteger
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_TColStd_0005fListOfInteger
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_TColStd_1ListOfInteger_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
