/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_V3d_0005fView */

#ifndef _Included_CASCADESamplesJni_V3d_0005fView
#define _Included_CASCADESamplesJni_V3d_0005fView
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ActiveLight
 * Signature: ()LCASCADESamplesJni/V3d_Light;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_ActiveLight
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ActivePlane
 * Signature: ()LCASCADESamplesJni/V3d_Plane;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_ActivePlane
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    AnimationMode
 * Signature: (Ljcas/Standard_Boolean;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_AnimationMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    AnimationModeIsOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_AnimationModeIsOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Antialiasing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_Antialiasing
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    At
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_At
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    BackFacingModel
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_BackFacingModel
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Center
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Center
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ColorScale
 * Signature: ()LCASCADESamplesJni/Aspect_ColorScale;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_ColorScale
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ColorScaleDisplay
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ColorScaleDisplay
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ColorScaleErase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ColorScaleErase
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ColorScaleIsDisplayed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_ColorScaleIsDisplayed
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ComputedMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_ComputedMode
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    DegenerateModeIsOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_DegenerateModeIsOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Depth
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_Depth
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    DoMapping
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_DoMapping
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    EnableDepthTest
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_EnableDepthTest
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    EnableGLLight
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_EnableGLLight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Eye
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Eye
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    FocalReferencePoint
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_FocalReferencePoint
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Focale
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_Focale
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IfMoreLights
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IfMoreLights
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IfMorePlanes
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IfMorePlanes
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IfWindow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IfWindow
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    InitActiveLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_InitActiveLights
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    InitActivePlanes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_InitActivePlanes
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IsActiveLight
 * Signature: (LCASCADESamplesJni/V3d_Light;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IsActiveLight
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IsActivePlane
 * Signature: (LCASCADESamplesJni/V3d_Plane;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IsActivePlane
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IsDepthTestEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IsDepthTestEnabled
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IsEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IsEmpty
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    IsGLLightEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_IsGLLightEnabled
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    MoreActiveLights
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_MoreActiveLights
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    MoreActivePlanes
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_MoreActivePlanes
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    MustBeResized
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_MustBeResized
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    NextActiveLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_NextActiveLights
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    NextActivePlanes
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_NextActivePlanes
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Pan
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Pan
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Panning
 * Signature: (DDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Panning
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Place
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Place
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Plot
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Plot
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Proj
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Proj
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ProjModel
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_ProjModel
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ProjReferenceAxe
 * Signature: (IILjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ProjReferenceAxe
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Project
 * Signature: (DDDLjcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Project
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Remove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Remove
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Reset
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Reset
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ResetViewMapping
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ResetViewMapping
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ResetViewOrientation
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ResetViewOrientation
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Rotation
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Rotation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Scale
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_Scale
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ScreenCopy
 * Signature: (LCASCADESamplesJni/PlotMgt_PlotterDriver;ZD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ScreenCopy
  (JNIEnv *, jobject, jobject, jboolean, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAnimationMode
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAnimationMode
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAnimationModeOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAnimationModeOff
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAnimationModeOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAnimationModeOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAntialiasingOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAntialiasingOff
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAntialiasingOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAntialiasingOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAt
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAt
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAxialScale
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAxialScale
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetAxis
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetAxis
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetBackFacingModel
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetBackFacingModel
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetBackgroundImage
 * Signature: (Ljcas/Standard_CString;SZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetBackgroundImage
  (JNIEnv *, jobject, jobject, jshort, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetBgImageStyle
 * Signature: (SZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetBgImageStyle
  (JNIEnv *, jobject, jshort, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetComputedMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetComputedMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetDegenerateModeOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetDegenerateModeOff
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetDegenerateModeOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetDegenerateModeOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetDepth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetEye
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetEye
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetFocale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetFocale
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetFront
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetGrid
 * Signature: (LCASCADESamplesJni/gp_Ax3;LCASCADESamplesJni/Aspect_Grid;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetGrid
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetGridActivity
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetGridActivity
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetGridGraphicValues
 * Signature: (LCASCADESamplesJni/Aspect_Grid;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetGridGraphicValues
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetMagnify
 * Signature: (LCASCADESamplesJni/Aspect_Window;LCASCADESamplesJni/V3d_View;IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetMagnify
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetPlotter
 * Signature: (LCASCADESamplesJni/Graphic3d_Plotter;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetPlotter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetProjModel
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetProjModel
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetScale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetScale
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetShadingModel
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetShadingModel
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetSurfaceDetail
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetSurfaceDetail
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetTextureEnv
 * Signature: (LCASCADESamplesJni/Graphic3d_TextureEnv;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetTextureEnv
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetTransparency
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetTransparency
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetTwist
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetTwist
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetViewMappingDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetViewMappingDefault
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetViewOrientationDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetViewOrientationDefault
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetVisualization
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetVisualization
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZClippingDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZClippingDepth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZClippingType
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZClippingType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZClippingWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZClippingWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZCueingDepth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZCueingDepth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZCueingOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZCueingOff
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZCueingOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZCueingOn
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZCueingWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZCueingWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZSize
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZSize
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SetZoom
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_SetZoom
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ShadingModel
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_ShadingModel
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Size
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Size
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    StartRotation
 * Signature: (IID)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_StartRotation
  (JNIEnv *, jobject, jint, jint, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    SurfaceDetail
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_SurfaceDetail
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TextureEnv
 * Signature: ()LCASCADESamplesJni/Graphic3d_TextureEnv;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_TextureEnv
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ToPixMap
 * Signature: (III)LCASCADESamplesJni/Aspect_PixMap;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_ToPixMap
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TransientManagerBeginAddDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_TransientManagerBeginAddDraw
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TransientManagerBeginDraw
 * Signature: (ZZ)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_TransientManagerBeginDraw
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TransientManagerClearDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_TransientManagerClearDraw
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Transparency
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_Transparency
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TriedronDisplay
 * Signature: (SSDS)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_TriedronDisplay
  (JNIEnv *, jobject, jshort, jshort, jdouble, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TriedronEcho
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_TriedronEcho
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    TriedronErase
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_TriedronErase
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Tumble
 * Signature: (IZ)D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_Tumble
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Twist
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_Twist
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_Type
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Up
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Up
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_Update
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    UpdateLights
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_UpdateLights
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_AxialScale_1
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1AxialScale_11
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_AxialScale_2
 * Signature: (IIS)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1AxialScale_12
  (JNIEnv *, jobject, jint, jint, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_BackgroundColor_1
 * Signature: (SLjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1BackgroundColor_11
  (JNIEnv *, jobject, jshort, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_BackgroundColor_2
 * Signature: ()LCASCADESamplesJni/Quantity_Color;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1BackgroundColor_12
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_ConvertToGrid_1
 * Signature: (IILjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1ConvertToGrid_11
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_ConvertToGrid_2
 * Signature: (DDDLjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1ConvertToGrid_12
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_1
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_11
  (JNIEnv *, jobject, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_2
 * Signature: (IILjcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_12
  (JNIEnv *, jobject, jint, jint, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_3
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_13
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_4
 * Signature: (DDLjcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_14
  (JNIEnv *, jobject, jdouble, jdouble, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_5
 * Signature: (IILjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_15
  (JNIEnv *, jobject, jint, jint, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Convert_6
 * Signature: (DDDLjcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Convert_16
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Dump_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Dump_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Dump_2
 * Signature: (Ljcas/Standard_CString;S)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Dump_12
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_FitAll_1
 * Signature: (DZZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1FitAll_11
  (JNIEnv *, jobject, jdouble, jboolean, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_FitAll_2
 * Signature: (DDDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1FitAll_12
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Move_1
 * Signature: (DDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Move_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Move_2
 * Signature: (SDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Move_12
  (JNIEnv *, jobject, jshort, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Move_3
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Move_13
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Redraw_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Redraw_11
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Redraw_2
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Redraw_12
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Rotate_1
 * Signature: (DDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Rotate_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Rotate_2
 * Signature: (DDDDDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Rotate_12
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Rotate_3
 * Signature: (SDDDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Rotate_13
  (JNIEnv *, jobject, jshort, jdouble, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Rotate_4
 * Signature: (SDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Rotate_14
  (JNIEnv *, jobject, jshort, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Rotate_5
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Rotate_15
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetBackgroundColor_1
 * Signature: (SDDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetBackgroundColor_11
  (JNIEnv *, jobject, jshort, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetBackgroundColor_2
 * Signature: (LCASCADESamplesJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetBackgroundColor_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetBackgroundColor_3
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetBackgroundColor_13
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetCenter_1
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetCenter_11
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetCenter_2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetCenter_12
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetLightOff_1
 * Signature: (LCASCADESamplesJni/V3d_Light;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetLightOff_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetLightOff_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetLightOff_12
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetLightOn_1
 * Signature: (LCASCADESamplesJni/V3d_Light;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetLightOn_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetLightOn_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetLightOn_12
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetPlaneOff_1
 * Signature: (LCASCADESamplesJni/V3d_Plane;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetPlaneOff_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetPlaneOff_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetPlaneOff_12
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetPlaneOn_1
 * Signature: (LCASCADESamplesJni/V3d_Plane;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetPlaneOn_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetPlaneOn_2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetPlaneOn_12
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetProj_1
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetProj_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetProj_2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetProj_12
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetUp_1
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetUp_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetUp_2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetUp_12
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_SetWindow_1
 * Signature: (LCASCADESamplesJni/Aspect_Window;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1SetWindow_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Translate_1
 * Signature: (DDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Translate_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Translate_2
 * Signature: (SDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Translate_12
  (JNIEnv *, jobject, jshort, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Translate_3
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Translate_13
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Turn_1
 * Signature: (DDDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Turn_11
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Turn_2
 * Signature: (SDZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Turn_12
  (JNIEnv *, jobject, jshort, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Turn_3
 * Signature: (DZ)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Turn_13
  (JNIEnv *, jobject, jdouble, jboolean);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Zoom_1
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Zoom_11
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    V3d_View_Zoom_2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_V3d_1View_1Zoom_12
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    View
 * Signature: ()LCASCADESamplesJni/Visual3d_View;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_View
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Viewer
 * Signature: ()LCASCADESamplesJni/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_Viewer
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Visualization
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_Visualization
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    Window
 * Signature: ()LCASCADESamplesJni/Aspect_Window;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_V3d_1View_Window
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    WindowFit
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_WindowFit
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    WindowFitAll
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_WindowFitAll
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ZBufferTriedronSetup
 * Signature: (SSSDDI)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ZBufferTriedronSetup
  (JNIEnv *, jobject, jshort, jshort, jshort, jdouble, jdouble, jint);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ZClipping
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_V3d_1View_ZClipping
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ZCueing
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_V3d_1View_ZCueing
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ZFitAll
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_V3d_1View_ZFitAll
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_V3d_0005fView
 * Method:    ZSize
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_V3d_1View_ZSize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
