/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Quantity_0005fColor */

#ifndef _Included_CASCADESamplesJni_Quantity_0005fColor
#define _Included_CASCADESamplesJni_Quantity_0005fColor
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Assign
 * Signature: (LCASCADESamplesJni/Quantity_Color;)LCASCADESamplesJni/Quantity_Color;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_Quantity_1Color_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Blue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Blue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    ChangeContrast
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_ChangeContrast
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    ChangeIntensity
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_ChangeIntensity
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Delta
 * Signature: (LCASCADESamplesJni/Quantity_Color;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Delta
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Distance
 * Signature: (LCASCADESamplesJni/Quantity_Color;)D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Distance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Epsilon
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Epsilon
  (JNIEnv *, jclass);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Green
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Green
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    HlsRgb
 * Signature: (DDDLjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_HlsRgb
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Hue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Hue
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    IsDifferent
 * Signature: (LCASCADESamplesJni/Quantity_Color;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_Quantity_1Color_IsDifferent
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    IsEqual
 * Signature: (LCASCADESamplesJni/Quantity_Color;)Z
 */
JNIEXPORT jboolean JNICALL Java_CASCADESamplesJni_Quantity_1Color_IsEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Light
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Light
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_Create_2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1Create_12
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_Create_3
 * Signature: (DDDS)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1Create_13
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jshort);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_Name_1
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1Name_11
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_Name_2
 * Signature: (DDD)S
 */
JNIEXPORT jshort JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1Name_12
  (JNIEnv *, jclass, jdouble, jdouble, jdouble);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_SetValues_1
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1SetValues_11
  (JNIEnv *, jobject, jshort);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Quantity_Color_SetValues_2
 * Signature: (DDDS)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Quantity_1Color_1SetValues_12
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jshort);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Red
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Red
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    RgbHls
 * Signature: (DDDLjcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_RgbHls
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jobject, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Saturation
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_Saturation
  (JNIEnv *, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    SetEpsilon
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_SetEpsilon
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    SquareDistance
 * Signature: (LCASCADESamplesJni/Quantity_Color;)D
 */
JNIEXPORT jdouble JNICALL Java_CASCADESamplesJni_Quantity_1Color_SquareDistance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    StringName
 * Signature: (S)Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_CASCADESamplesJni_Quantity_1Color_StringName
  (JNIEnv *, jclass, jshort);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Test
  (JNIEnv *, jclass);

/*
 * Class:     CASCADESamplesJni_Quantity_0005fColor
 * Method:    Values
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_Real;Ljcas/Standard_Real;S)V
 */
JNIEXPORT void JNICALL Java_CASCADESamplesJni_Quantity_1Color_Values
  (JNIEnv *, jobject, jobject, jobject, jobject, jshort);

#ifdef __cplusplus
}
#endif
#endif
