/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Aspect_0005fGridType */

#ifndef _Included_CASCADESamplesJni_Aspect_0005fGridType
#define _Included_CASCADESamplesJni_Aspect_0005fGridType
#ifdef __cplusplus
extern "C" {
#endif
#undef CASCADESamplesJni_Aspect_0005fGridType_Aspect_GT_Rectangular
#define CASCADESamplesJni_Aspect_0005fGridType_Aspect_GT_Rectangular 0L
#undef CASCADESamplesJni_Aspect_0005fGridType_Aspect_GT_Circular
#define CASCADESamplesJni_Aspect_0005fGridType_Aspect_GT_Circular 1L
#ifdef __cplusplus
}
#endif
#endif
