/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Graphic3d_0005fAspectMarker3d */

#ifndef _Included_CASCADESamplesJni_Graphic3d_0005fAspectMarker3d
#define _Included_CASCADESamplesJni_Graphic3d_0005fAspectMarker3d
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
