/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Aspect_0005fWindow */

#ifndef _Included_CASCADESamplesJni_Aspect_0005fWindow
#define _Included_CASCADESamplesJni_Aspect_0005fWindow
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
