/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CASCADESamplesJni_Graphic2d_0005fGraphicObject */

#ifndef _Included_CASCADESamplesJni_Graphic2d_0005fGraphicObject
#define _Included_CASCADESamplesJni_Graphic2d_0005fGraphicObject
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
