// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _Handle_ISession2D_ObjectOwner_HeaderFile
#define _Handle_ISession2D_ObjectOwner_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_SelectMgr_EntityOwner_HeaderFile
#include <Handle_SelectMgr_EntityOwner.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(SelectMgr_EntityOwner);
class ISession2D_ObjectOwner;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(ISession2D_ObjectOwner);

class Handle(ISession2D_ObjectOwner) : public Handle(SelectMgr_EntityOwner) {
  public:
    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
    Handle(ISession2D_ObjectOwner)():Handle(SelectMgr_EntityOwner)() {} 
    Handle(ISession2D_ObjectOwner)(const Handle(ISession2D_ObjectOwner)& aHandle) : Handle(SelectMgr_EntityOwner)(aHandle) 
     {
     }

    Handle(ISession2D_ObjectOwner)(const ISession2D_ObjectOwner* anItem) : Handle(SelectMgr_EntityOwner)((SelectMgr_EntityOwner *)anItem) 
     {
     }

    Handle(ISession2D_ObjectOwner)& operator=(const Handle(ISession2D_ObjectOwner)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(ISession2D_ObjectOwner)& operator=(const ISession2D_ObjectOwner* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    ISession2D_ObjectOwner* operator->() 
     {
      return (ISession2D_ObjectOwner *)ControlAccess();
     }

    ISession2D_ObjectOwner* operator->() const 
     {
      return (ISession2D_ObjectOwner *)ControlAccess();
     }

   Standard_EXPORT ~Handle(ISession2D_ObjectOwner)();
 
   Standard_EXPORT static const Handle(ISession2D_ObjectOwner) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
