// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _Handle_ISession2D_Shape_HeaderFile
#define _Handle_ISession2D_Shape_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_AIS_InteractiveObject_HeaderFile
#include <Handle_AIS_InteractiveObject.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(AIS_InteractiveObject);
class ISession2D_Shape;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(ISession2D_Shape);

class Handle(ISession2D_Shape) : public Handle(AIS_InteractiveObject) {
  public:
    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
    Handle(ISession2D_Shape)():Handle(AIS_InteractiveObject)() {} 
    Handle(ISession2D_Shape)(const Handle(ISession2D_Shape)& aHandle) : Handle(AIS_InteractiveObject)(aHandle) 
     {
     }

    Handle(ISession2D_Shape)(const ISession2D_Shape* anItem) : Handle(AIS_InteractiveObject)((AIS_InteractiveObject *)anItem) 
     {
     }

    Handle(ISession2D_Shape)& operator=(const Handle(ISession2D_Shape)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(ISession2D_Shape)& operator=(const ISession2D_Shape* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    ISession2D_Shape* operator->() 
     {
      return (ISession2D_Shape *)ControlAccess();
     }

    ISession2D_Shape* operator->() const 
     {
      return (ISession2D_Shape *)ControlAccess();
     }

   Standard_EXPORT ~Handle(ISession2D_Shape)();
 
   Standard_EXPORT static const Handle(ISession2D_Shape) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
