// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _ISession2D_Shape_HeaderFile
#define _ISession2D_Shape_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_ISession2D_Shape_HeaderFile
#include <Handle_ISession2D_Shape.hxx>
#endif

#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _TopTools_ListOfShape_HeaderFile
#include <TopTools_ListOfShape.hxx>
#endif
#ifndef _HLRAlgo_Projector_HeaderFile
#include <HLRAlgo_Projector.hxx>
#endif
#ifndef _Handle_HLRBRep_Algo_HeaderFile
#include <Handle_HLRBRep_Algo.hxx>
#endif
#ifndef _Handle_HLRBRep_PolyAlgo_HeaderFile
#include <Handle_HLRBRep_PolyAlgo.hxx>
#endif
#ifndef _AIS_InteractiveObject_HeaderFile
#include <AIS_InteractiveObject.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_PrsMgr_PresentationManager3d_HeaderFile
#include <Handle_PrsMgr_PresentationManager3d.hxx>
#endif
#ifndef _Handle_Prs3d_Presentation_HeaderFile
#include <Handle_Prs3d_Presentation.hxx>
#endif
#ifndef _Handle_Prs3d_Projector_HeaderFile
#include <Handle_Prs3d_Projector.hxx>
#endif
#ifndef _Handle_PrsMgr_PresentationManager2d_HeaderFile
#include <Handle_PrsMgr_PresentationManager2d.hxx>
#endif
#ifndef _Handle_Graphic2d_GraphicObject_HeaderFile
#include <Handle_Graphic2d_GraphicObject.hxx>
#endif
#ifndef _Handle_Graphic2d_SetOfSegments_HeaderFile
#include <Handle_Graphic2d_SetOfSegments.hxx>
#endif
#ifndef _Handle_GGraphic2d_SetOfCurves_HeaderFile
#include <Handle_GGraphic2d_SetOfCurves.hxx>
#endif
#ifndef _Handle_SelectMgr_Selection_HeaderFile
#include <Handle_SelectMgr_Selection.hxx>
#endif
class HLRBRep_Algo;
class HLRBRep_PolyAlgo;
class TopoDS_Shape;
class HLRAlgo_Projector;
class PrsMgr_PresentationManager3d;
class Prs3d_Presentation;
class Prs3d_Projector;
class PrsMgr_PresentationManager2d;
class Graphic2d_GraphicObject;
class Graphic2d_SetOfSegments;
class GGraphic2d_SetOfCurves;
class SelectMgr_Selection;


class ISession2D_Shape : public AIS_InteractiveObject {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT ISession2D_Shape();
Standard_EXPORT   void Add(const TopoDS_Shape& aShape) ;
Standard_EXPORT   HLRAlgo_Projector Projector() ;
Standard_EXPORT   void SetProjector(HLRAlgo_Projector& aProjector) ;
Standard_EXPORT   Standard_Integer NbIsos() ;
Standard_EXPORT   void SetNbIsos(const Standard_Integer aNbIsos) ;
Standard_EXPORT virtual  Standard_Boolean AcceptShapeDecomposition() ;
Standard_EXPORT   Standard_Boolean AcceptSelectionMode(const Standard_Integer aMode) ;
Standard_EXPORT   void BuildAlgo() ;
Standard_EXPORT   void BuildPolyAlgo() ;
Standard_EXPORT virtual  void Compute(const Handle(PrsMgr_PresentationManager3d)& aPresentationManager,const Handle(Prs3d_Presentation)& aPresentation,const Standard_Integer aMode = 0) ;
Standard_EXPORT virtual  void Compute(const Handle(Prs3d_Projector)& aProjector,const Handle(Prs3d_Presentation)& aPresentation) ;
Standard_EXPORT virtual  void Compute(const Handle(PrsMgr_PresentationManager2d)& aPresentationManager,const Handle(Graphic2d_GraphicObject)& aGrObj,const Standard_Integer aMode = 0) ;
Standard_EXPORT   void DrawCompound(const TopoDS_Shape& aCompound,const Handle(Graphic2d_SetOfSegments)& aSetOfSegments) ;
Standard_EXPORT   void DrawCompound(const TopoDS_Shape& aCompound,const Handle(GGraphic2d_SetOfCurves)& aSetOfCurves) ;
Standard_EXPORT virtual  void ComputeSelection(const Handle(SelectMgr_Selection)& aSelection,const Standard_Integer aMode) ;
Standard_EXPORT ~ISession2D_Shape();




 // Type management
 //
 Standard_EXPORT friend Handle_Standard_Type& ISession2D_Shape_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //
Standard_Integer myNbIsos;
TopTools_ListOfShape myListOfShape;
HLRAlgo_Projector myProjector;
Handle_HLRBRep_Algo myAlgo;
Handle_HLRBRep_PolyAlgo myPolyAlgo;


};


#include <ISession2D_Shape.lxx>



// other Inline functions and methods (like "C++: function call" methods)
//


#endif
