// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _ISession_Text_HeaderFile
#define _ISession_Text_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_ISession_Text_HeaderFile
#include <Handle_ISession_Text.hxx>
#endif

#ifndef _TCollection_AsciiString_HeaderFile
#include <TCollection_AsciiString.hxx>
#endif
#ifndef _Standard_Real_HeaderFile
#include <Standard_Real.hxx>
#endif
#ifndef _Aspect_TypeOfText_HeaderFile
#include <Aspect_TypeOfText.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Quantity_Factor_HeaderFile
#include <Quantity_Factor.hxx>
#endif
#ifndef _AIS_InteractiveObject_HeaderFile
#include <AIS_InteractiveObject.hxx>
#endif
#ifndef _Quantity_PlaneAngle_HeaderFile
#include <Quantity_PlaneAngle.hxx>
#endif
#ifndef _Handle_PrsMgr_PresentationManager3d_HeaderFile
#include <Handle_PrsMgr_PresentationManager3d.hxx>
#endif
#ifndef _Handle_Prs3d_Presentation_HeaderFile
#include <Handle_Prs3d_Presentation.hxx>
#endif
#ifndef _Handle_Prs3d_Projector_HeaderFile
#include <Handle_Prs3d_Projector.hxx>
#endif
#ifndef _Handle_PrsMgr_PresentationManager2d_HeaderFile
#include <Handle_PrsMgr_PresentationManager2d.hxx>
#endif
#ifndef _Handle_Graphic2d_GraphicObject_HeaderFile
#include <Handle_Graphic2d_GraphicObject.hxx>
#endif
#ifndef _Handle_SelectMgr_Selection_HeaderFile
#include <Handle_SelectMgr_Selection.hxx>
#endif
class TCollection_AsciiString;
class gp_Pnt;
class PrsMgr_PresentationManager3d;
class Prs3d_Presentation;
class Prs3d_Projector;
class PrsMgr_PresentationManager2d;
class Graphic2d_GraphicObject;
class SelectMgr_Selection;


class ISession_Text : public AIS_InteractiveObject {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT ISession_Text();
Standard_EXPORT ISession_Text(const TCollection_AsciiString& aText,const Standard_Real anX = 0,const Standard_Real anY = 0,const Standard_Real aZ = 0,const Aspect_TypeOfText aType = Aspect_TOT_SOLID,const Quantity_PlaneAngle anAngle = 0.0,const Standard_Real aSlant = 0.0,const Standard_Integer aColorIndex = 1,const Standard_Integer aFontIndex = 1,const Quantity_Factor aScale = 0.1);
Standard_EXPORT ISession_Text(const TCollection_AsciiString& aText,const gp_Pnt& aPoint,const Aspect_TypeOfText aType = Aspect_TOT_SOLID,const Quantity_PlaneAngle anAngle = 0.0,const Standard_Real aSlant = 0.0,const Standard_Integer aColorIndex = 1,const Standard_Integer aFontIndex = 1,const Quantity_Factor aScale = 0.1);
Standard_EXPORT virtual  Standard_Integer NbPossibleSelection() ;
Standard_EXPORT   TCollection_AsciiString GetText() ;
Standard_EXPORT   void SetText(const TCollection_AsciiString& aText) ;
Standard_EXPORT   void GetCoord(Standard_Real& X,Standard_Real& Y,Standard_Real& Z) ;
Standard_EXPORT   void SetCoord(const Standard_Real X,const Standard_Real Y,const Standard_Real Z) ;
Standard_EXPORT   Aspect_TypeOfText GetTypeOfText() ;
Standard_EXPORT   void SetTypeOfText(const Aspect_TypeOfText aNewTypeOfText) ;
Standard_EXPORT   Standard_Real GetAngle() ;
Standard_EXPORT   void SetAngle(const Standard_Real aNewAngle) ;
Standard_EXPORT   Standard_Real GetSlant() ;
Standard_EXPORT   void SetSlant(const Standard_Real aNewSlant) ;
Standard_EXPORT   Standard_Integer GetColorIndex() ;
Standard_EXPORT   void SetColorIndex(const Standard_Integer aNewColorIndex) ;
Standard_EXPORT   Standard_Integer GetFontIndex() ;
Standard_EXPORT   void SetFontIndex(const Standard_Integer aNewFontIndex) ;
Standard_EXPORT   Quantity_Factor GetScale() ;
Standard_EXPORT   void SetScale(const Quantity_Factor aNewScale) ;
Standard_EXPORT ~ISession_Text();




 // Type management
 //
 Standard_EXPORT friend Handle_Standard_Type& ISession_Text_Type_();
 Standard_EXPORT const Handle(Standard_Type)& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 
Standard_EXPORT virtual  void Compute(const Handle(PrsMgr_PresentationManager3d)& aPresentationManager,const Handle(Prs3d_Presentation)& aPresentation,const Standard_Integer aMode) ;
Standard_EXPORT virtual  void Compute(const Handle(Prs3d_Projector)& aProjector,const Handle(Prs3d_Presentation)& aPresentation) ;
Standard_EXPORT virtual  void Compute(const Handle(PrsMgr_PresentationManager2d)& aPresentationManager,const Handle(Graphic2d_GraphicObject)& aGrObj,const Standard_Integer unMode = 0) ;
Standard_EXPORT virtual  void ComputeSelection(const Handle(SelectMgr_Selection)& aSelection,const Standard_Integer unMode) ;


 // Fields PRIVATE
 //
TCollection_AsciiString MyText;
Standard_Real MyX;
Standard_Real MyY;
Standard_Real MyZ;
Aspect_TypeOfText MyTypeOfText;
Standard_Real MyAngle;
Standard_Real MySlant;
Standard_Integer MyColorIndex;
Standard_Integer MyFontIndex;
Quantity_Factor MyScale;
Standard_Real MyWidth;
Standard_Real MyHeight;


};


#include <ISession_Text.lxx>



// other Inline functions and methods (like "C++: function call" methods)
//


#endif
