/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_V2d_0005fDefaultMap */

#ifndef _Included_SampleHLRJni_V2d_0005fDefaultMap
#define _Included_SampleHLRJni_V2d_0005fDefaultMap
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    ColorMap
 * Signature: ()LSampleHLRJni/Aspect_GenericColorMap;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_V2d_1DefaultMap_ColorMap
  (JNIEnv *, jclass);

/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_V2d_1DefaultMap_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    FontMap
 * Signature: ()LSampleHLRJni/Aspect_FontMap;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_V2d_1DefaultMap_FontMap
  (JNIEnv *, jclass);

/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    MarkMap
 * Signature: ()LSampleHLRJni/Aspect_MarkMap;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_V2d_1DefaultMap_MarkMap
  (JNIEnv *, jclass);

/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    TypeMap
 * Signature: ()LSampleHLRJni/Aspect_TypeMap;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_V2d_1DefaultMap_TypeMap
  (JNIEnv *, jclass);

/*
 * Class:     SampleHLRJni_V2d_0005fDefaultMap
 * Method:    WidthMap
 * Signature: ()LSampleHLRJni/Aspect_WidthMap;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_V2d_1DefaultMap_WidthMap
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
