/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_AlienImage_0005fAlienImage */

#ifndef _Included_SampleViewer3DJni_AlienImage_0005fAlienImage
#define _Included_SampleViewer3DJni_AlienImage_0005fAlienImage
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
