/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_Graphic3d_0005fArray1OfVertexC */

#ifndef _Included_SampleViewer3DJni_Graphic3d_0005fArray1OfVertexC
#define _Included_SampleViewer3DJni_Graphic3d_0005fArray1OfVertexC
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fArray1OfVertexC
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1Array1OfVertexC_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
