// File generated by CPPExt (Value)
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _SampleImportExportPackage_HeaderFile
#define _SampleImportExportPackage_HeaderFile

#ifndef _Handle_V3d_Viewer_HeaderFile
#include <Handle_V3d_Viewer.hxx>
#endif
#ifndef _Standard_ExtString_HeaderFile
#include <Standard_ExtString.hxx>
#endif
#ifndef _Handle_V3d_View_HeaderFile
#include <Handle_V3d_View.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Standard_CString_HeaderFile
#include <Standard_CString.hxx>
#endif
#ifndef _Handle_AIS_InteractiveContext_HeaderFile
#include <Handle_AIS_InteractiveContext.hxx>
#endif
#ifndef _MgtBRep_TriangleMode_HeaderFile
#include <MgtBRep_TriangleMode.hxx>
#endif
#ifndef _IFSelect_ReturnStatus_HeaderFile
#include <IFSelect_ReturnStatus.hxx>
#endif
#ifndef _STEPControl_StepModelType_HeaderFile
#include <STEPControl_StepModelType.hxx>
#endif
class V3d_Viewer;
class V3d_View;
class AIS_InteractiveContext;
class TCollection_AsciiString;


#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

class SampleImportExportPackage  {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT static  Handle_V3d_Viewer CreateViewer3d(const Standard_ExtString aName) ;
Standard_EXPORT static  void SetWindow3d(const Handle(V3d_View)& aView,const Standard_Integer hiwin,const Standard_Integer lowin) ;
Standard_EXPORT static  Standard_Boolean ReadBREP(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext) ;
Standard_EXPORT static  Standard_Boolean SaveBREP(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext) ;
Standard_EXPORT static  Standard_Boolean ReadCSFDB(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext,TCollection_AsciiString& ReturnMessage) ;
Standard_EXPORT static  Standard_Boolean SaveCSFDB(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext,TCollection_AsciiString& ReturnMessage,const MgtBRep_TriangleMode aTriangleMode = MgtBRep_WithTriangle) ;
Standard_EXPORT static  IFSelect_ReturnStatus ReadSTEP(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext) ;
Standard_EXPORT static  IFSelect_ReturnStatus SaveSTEP(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext,const STEPControl_StepModelType aValue = STEPControl_AsIs) ;
Standard_EXPORT static  Standard_Integer ReadIGES(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext) ;
Standard_EXPORT static  Standard_Boolean SaveIGES(const Standard_CString aFileName,const Handle(AIS_InteractiveContext)& aContext) ;
Standard_EXPORT static  Standard_Boolean SaveImage(const Standard_CString aFileName,const Standard_CString aFormat,const Handle(V3d_View)& aView) ;





protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
