/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SamplesTopologyJni_SamplesTopologyPackage */

#ifndef _Included_SamplesTopologyJni_SamplesTopologyPackage
#define _Included_SamplesTopologyJni_SamplesTopologyPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Blend
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Blend
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    BuildMesh
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_BuildMesh
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Builder
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Builder
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Chamfer
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Chamfer
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    ClearMesh
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_ClearMesh
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Common
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Common
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Compound
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Compound
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    CreateViewer
 * Signature: (Ljava/lang/String;)LSamplesTopologyJni/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_CreateViewer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Cut
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Cut
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Deform
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Deform
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Displacement
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Displacement
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    DisplayMesh
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_DisplayMesh
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Edge
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Edge
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    EvolvedBlend
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_EvolvedBlend
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Explorer
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Explorer
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Face
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Face
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Fuse
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Fuse
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Geometry
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Geometry
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Glue
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Glue
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    LinearProp
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_LinearProp
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    LocalDPrism
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_LocalDPrism
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    LocalPipe
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_LocalPipe
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    LocalPrism
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_LocalPrism
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    LocalRevol
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_LocalRevol
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeBox
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeBox
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeCone
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeCone
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeCylinder
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeCylinder
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeDraft
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeDraft
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeEvolved
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeEvolved
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakePipe
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakePipe
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakePrism
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakePrism
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeRevol
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeRevol
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeSphere
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeSphere
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeThru
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeThru
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeTorus
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeTorus
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    MakeWedge
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_MakeWedge
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Mirror
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Mirror
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Mirroraxis
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Mirroraxis
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Offset
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Offset
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    PSection
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_PSection
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Rib
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Rib
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Rotate
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Rotate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Scale
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Scale
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Section
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Section
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    SetWindow
 * Signature: (LSamplesTopologyJni/V3d_View;II)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_SetWindow
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Sewing
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Sewing
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Shell
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Shell
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Split
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Split
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    SurfaceProp
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_SurfaceProp
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Thick
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Thick
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Translation
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Translation
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Validity
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Validity
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Vertex
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Vertex
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    VolumeProp
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_VolumeProp
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SamplesTopologyJni_SamplesTopologyPackage
 * Method:    Wire
 * Signature: (LSamplesTopologyJni/AIS_InteractiveContext;LSamplesTopologyJni/TCollection_AsciiString;)V
 */
JNIEXPORT void JNICALL Java_SamplesTopologyJni_SamplesTopologyPackage_Wire
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
