/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_TCollection_0005fAsciiString */

#ifndef _Included_SampleViewer3DJni_TCollection_0005fAsciiString
#define _Included_SampleViewer3DJni_TCollection_0005fAsciiString
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_TCollection_0005fAsciiString
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_TCollection_1AsciiString_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
