/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_TColStd_0005fArray1OfReal */

#ifndef _Included_SampleHLRJni_TColStd_0005fArray1OfReal
#define _Included_SampleHLRJni_TColStd_0005fArray1OfReal
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_TColStd_0005fArray1OfReal
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColStd_1Array1OfReal_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
