/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fWidthMapEntry */

#ifndef _Included_SampleHLRJni_Aspect_0005fWidthMapEntry
#define _Included_SampleHLRJni_Aspect_0005fWidthMapEntry
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_Create_2
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1Create_12
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_Create_3
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1Create_13
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_Create_4
 * Signature: (LSampleHLRJni/Aspect_WidthMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1Create_14
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_SetValue_1
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1SetValue_11
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_SetValue_2
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1SetValue_12
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Aspect_WidthMapEntry_SetValue_3
 * Signature: (LSampleHLRJni/Aspect_WidthMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Aspect_1WidthMapEntry_1SetValue_13
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Dump
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Free
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Index
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    IsAllocated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_IsAllocated
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    SetIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_SetIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    SetType
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_SetType
  (JNIEnv *, jobject, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    SetWidth
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_SetWidth
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Type
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWidthMapEntry
 * Method:    Width
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_SampleHLRJni_Aspect_1WidthMapEntry_Width
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
