/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_Graphic3d_0005fTypeOfComposition */

#ifndef _Included_SampleViewer3DJni_Graphic3d_0005fTypeOfComposition
#define _Included_SampleViewer3DJni_Graphic3d_0005fTypeOfComposition
#ifdef __cplusplus
extern "C" {
#endif
#undef SampleViewer3DJni_Graphic3d_0005fTypeOfComposition_Graphic3d_TOC_REPLACE
#define SampleViewer3DJni_Graphic3d_0005fTypeOfComposition_Graphic3d_TOC_REPLACE 0L
#undef SampleViewer3DJni_Graphic3d_0005fTypeOfComposition_Graphic3d_TOC_POSTCONCATENATE
#define SampleViewer3DJni_Graphic3d_0005fTypeOfComposition_Graphic3d_TOC_POSTCONCATENATE 1L
#ifdef __cplusplus
}
#endif
#endif
