/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_TColStd_0005fArray2OfReal */

#ifndef _Included_SampleViewer3DJni_TColStd_0005fArray2OfReal
#define _Included_SampleViewer3DJni_TColStd_0005fArray2OfReal
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_TColStd_0005fArray2OfReal
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_TColStd_1Array2OfReal_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
