/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fWindowDriver */

#ifndef _Included_SampleHLRJni_Aspect_0005fWindowDriver
#define _Included_SampleHLRJni_Aspect_0005fWindowDriver
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    AngleOfBuffer
 * Signature: (ILjcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_AngleOfBuffer
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    Aspect_WindowDriver_TextSize_1
 * Signature: (LSampleHLRJni/TCollection_ExtendedString;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_Aspect_1WindowDriver_1TextSize_11
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    Aspect_WindowDriver_TextSize_2
 * Signature: (LSampleHLRJni/TCollection_ExtendedString;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_Aspect_1WindowDriver_1TextSize_12
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    BeginDraw
 * Signature: (ZI)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_BeginDraw
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    BufferIsDrawn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_BufferIsDrawn
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    BufferIsEmpty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_BufferIsEmpty
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    BufferIsOpen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_BufferIsOpen
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    ClearBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_ClearBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    CloseBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_CloseBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    ColorBoundIndexs
 * Signature: (Ljcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_ColorBoundIndexs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    DrawBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_DrawBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    EraseBuffer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_EraseBuffer
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    FontBoundIndexs
 * Signature: (Ljcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_FontBoundIndexs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    FontSize
 * Signature: (Ljcas/Standard_Real;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;I)Ljcas/Standard_CString;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_FontSize
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    LocalColorIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_LocalColorIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    LocalFontIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_LocalFontIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    LocalMarkIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_LocalMarkIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    LocalTypeIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_LocalTypeIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    LocalWidthIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_LocalWidthIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    MarkBoundIndexs
 * Signature: (Ljcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_MarkBoundIndexs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    MoveBuffer
 * Signature: (IFF)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_MoveBuffer
  (JNIEnv *, jobject, jint, jfloat, jfloat);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    OpenBuffer
 * Signature: (IFFIIIS)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_OpenBuffer
  (JNIEnv *, jobject, jint, jfloat, jfloat, jint, jint, jint, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    PositionOfBuffer
 * Signature: (ILjcas/Standard_ShortReal;Ljcas/Standard_ShortReal;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_PositionOfBuffer
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    ResizeSpace
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_ResizeSpace
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    RotateBuffer
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_RotateBuffer
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    ScaleBuffer
 * Signature: (IDD)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_ScaleBuffer
  (JNIEnv *, jobject, jint, jdouble, jdouble);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    ScaleOfBuffer
 * Signature: (ILjcas/Standard_Real;Ljcas/Standard_Real;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_ScaleOfBuffer
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    SetDrawMode
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_SetDrawMode
  (JNIEnv *, jobject, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    TypeBoundIndexs
 * Signature: (Ljcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_TypeBoundIndexs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    WidthBoundIndexs
 * Signature: (Ljcas/Standard_Integer;Ljcas/Standard_Integer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_WidthBoundIndexs
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fWindowDriver
 * Method:    Window
 * Signature: ()LSampleHLRJni/Aspect_Window;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1WindowDriver_Window
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
