/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fFontMapEntry */

#ifndef _Included_SampleHLRJni_Aspect_0005fFontMapEntry
#define _Included_SampleHLRJni_Aspect_0005fFontMapEntry
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Aspect_FontMapEntry_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Aspect_1FontMapEntry_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Aspect_FontMapEntry_Create_2
 * Signature: (ILSampleHLRJni/Aspect_FontStyle;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Aspect_1FontMapEntry_1Create_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Aspect_FontMapEntry_Create_3
 * Signature: (LSampleHLRJni/Aspect_FontMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Aspect_1FontMapEntry_1Create_13
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Aspect_FontMapEntry_SetValue_1
 * Signature: (ILSampleHLRJni/Aspect_FontStyle;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Aspect_1FontMapEntry_1SetValue_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Aspect_FontMapEntry_SetValue_2
 * Signature: (LSampleHLRJni/Aspect_FontMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Aspect_1FontMapEntry_1SetValue_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Dump
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Free
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Index
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    IsAllocated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_IsAllocated
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    SetIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_SetIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    SetType
 * Signature: (LSampleHLRJni/Aspect_FontStyle;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_SetType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMapEntry
 * Method:    Type
 * Signature: ()LSampleHLRJni/Aspect_FontStyle;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1FontMapEntry_Type
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
