/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fMarkMap */

#ifndef _Included_SampleHLRJni_Aspect_0005fMarkMap
#define _Included_SampleHLRJni_Aspect_0005fMarkMap
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Aspect_MarkMap_AddEntry_1
 * Signature: (LSampleHLRJni/Aspect_MarkMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Aspect_1MarkMap_1AddEntry_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Aspect_MarkMap_AddEntry_2
 * Signature: (LSampleHLRJni/Aspect_MarkerStyle;)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Aspect_1MarkMap_1AddEntry_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Aspect_MarkMap_Create_0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Aspect_1MarkMap_1Create_10
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Dump
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Entry
 * Signature: (I)LSampleHLRJni/Aspect_MarkMapEntry;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Entry
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Index
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Index
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkMap
 * Method:    Size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1MarkMap_Size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
