/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fColorMapEntry */

#ifndef _Included_SampleHLRJni_Aspect_0005fColorMapEntry
#define _Included_SampleHLRJni_Aspect_0005fColorMapEntry
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Aspect_ColorMapEntry_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Aspect_1ColorMapEntry_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Aspect_ColorMapEntry_Create_2
 * Signature: (ILSampleHLRJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Aspect_1ColorMapEntry_1Create_12
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Aspect_ColorMapEntry_Create_3
 * Signature: (LSampleHLRJni/Aspect_ColorMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Aspect_1ColorMapEntry_1Create_13
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Aspect_ColorMapEntry_SetValue_1
 * Signature: (ILSampleHLRJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Aspect_1ColorMapEntry_1SetValue_11
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Aspect_ColorMapEntry_SetValue_2
 * Signature: (LSampleHLRJni/Aspect_ColorMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Aspect_1ColorMapEntry_1SetValue_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Color
 * Signature: ()LSampleHLRJni/Quantity_Color;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Color
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Dump
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Free
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    Index
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_Index
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    IsAllocated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_IsAllocated
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    SetColor
 * Signature: (LSampleHLRJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_SetColor
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fColorMapEntry
 * Method:    SetIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1ColorMapEntry_SetIndex
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
