/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fGenericColorMap */

#ifndef _Included_SampleHLRJni_Aspect_0005fGenericColorMap
#define _Included_SampleHLRJni_Aspect_0005fGenericColorMap
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    Aspect_GenericColorMap_AddEntry_1
 * Signature: (LSampleHLRJni/Aspect_ColorMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_Aspect_1GenericColorMap_1AddEntry_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    Aspect_GenericColorMap_AddEntry_2
 * Signature: (LSampleHLRJni/Quantity_Color;)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_Aspect_1GenericColorMap_1AddEntry_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    Aspect_GenericColorMap_Create_0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_Aspect_1GenericColorMap_1Create_10
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    FindColorMapIndex
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_FindColorMapIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    FindEntry
 * Signature: (I)LSampleHLRJni/Aspect_ColorMapEntry;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_FindEntry
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    NearestColorMapIndex
 * Signature: (LSampleHLRJni/Quantity_Color;)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_NearestColorMapIndex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    NearestEntry
 * Signature: (LSampleHLRJni/Quantity_Color;)LSampleHLRJni/Aspect_ColorMapEntry;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_NearestEntry
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fGenericColorMap
 * Method:    RemoveEntry
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1GenericColorMap_RemoveEntry
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
