/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_Aspect_0005fArray1OfEdge */

#ifndef _Included_SampleViewer3DJni_Aspect_0005fArray1OfEdge
#define _Included_SampleViewer3DJni_Aspect_0005fArray1OfEdge
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_Aspect_0005fArray1OfEdge
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Aspect_1Array1OfEdge_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
