/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fTypeOfLine */

#ifndef _Included_SampleHLRJni_Aspect_0005fTypeOfLine
#define _Included_SampleHLRJni_Aspect_0005fTypeOfLine
#ifdef __cplusplus
extern "C" {
#endif
#undef SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_SOLID
#define SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_SOLID 0L
#undef SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DASH
#define SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DASH 1L
#undef SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DOT
#define SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DOT 2L
#undef SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DOTDASH
#define SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_DOTDASH 3L
#undef SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_USERDEFINED
#define SampleHLRJni_Aspect_0005fTypeOfLine_Aspect_TOL_USERDEFINED 4L
#ifdef __cplusplus
}
#endif
#endif
