/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleAISSelectJni_Standard_0005fStorable */

#ifndef _Included_SampleAISSelectJni_Standard_0005fStorable
#define _Included_SampleAISSelectJni_Standard_0005fStorable
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
