/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleDisplayAnimationJni_SampleDisplayAnimationPackage */

#ifndef _Included_SampleDisplayAnimationJni_SampleDisplayAnimationPackage
#define _Included_SampleDisplayAnimationJni_SampleDisplayAnimationPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    ChangePosition
 * Signature: (LSampleDisplayAnimationJni/AIS_InteractiveContext;)V
 */
JNIEXPORT void JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_ChangePosition
  (JNIEnv *, jclass, jobject);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    CreateViewer
 * Signature: (Ljava/lang/String;)LSampleDisplayAnimationJni/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_CreateViewer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    GetAngleIncrement
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_GetAngleIncrement
  (JNIEnv *, jclass);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    GetDeviationCoefficient
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_GetDeviationCoefficient
  (JNIEnv *, jclass);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    LoadData
 * Signature: (LSampleDisplayAnimationJni/AIS_InteractiveContext;Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_LoadData
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    SaveImage
 * Signature: (Ljcas/Standard_CString;Ljcas/Standard_CString;LSampleDisplayAnimationJni/V3d_View;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_SaveImage
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    SetAngleIncrement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_SetAngleIncrement
  (JNIEnv *, jclass, jint);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    SetDeviationCoefficient
 * Signature: (LSampleDisplayAnimationJni/AIS_InteractiveContext;D)V
 */
JNIEXPORT void JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_SetDeviationCoefficient
  (JNIEnv *, jclass, jobject, jdouble);

/*
 * Class:     SampleDisplayAnimationJni_SampleDisplayAnimationPackage
 * Method:    SetWindow
 * Signature: (LSampleDisplayAnimationJni/V3d_View;II)V
 */
JNIEXPORT void JNICALL Java_SampleDisplayAnimationJni_SampleDisplayAnimationPackage_SetWindow
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
