/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleAISBasicJni_UnitsAPI */

#ifndef _Included_SampleAISBasicJni_UnitsAPI
#define _Included_SampleAISBasicJni_UnitsAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleAISBasicJni_UnitsAPI
 * Method:    SetLocalSystem
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_SampleAISBasicJni_UnitsAPI_SetLocalSystem
  (JNIEnv *, jclass, jshort);

#ifdef __cplusplus
}
#endif
#endif
