/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fTypeOfText */

#ifndef _Included_SampleHLRJni_Aspect_0005fTypeOfText
#define _Included_SampleHLRJni_Aspect_0005fTypeOfText
#ifdef __cplusplus
extern "C" {
#endif
#undef SampleHLRJni_Aspect_0005fTypeOfText_Aspect_TOT_SOLID
#define SampleHLRJni_Aspect_0005fTypeOfText_Aspect_TOT_SOLID 0L
#undef SampleHLRJni_Aspect_0005fTypeOfText_Aspect_TOT_OUTLINE
#define SampleHLRJni_Aspect_0005fTypeOfText_Aspect_TOT_OUTLINE 1L
#ifdef __cplusplus
}
#endif
#endif
