/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fBackground */

#ifndef _Included_SampleHLRJni_Aspect_0005fBackground
#define _Included_SampleHLRJni_Aspect_0005fBackground
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fBackground
 * Method:    Aspect_Background_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1Background_Aspect_1Background_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fBackground
 * Method:    Aspect_Background_Create_2
 * Signature: (LSampleHLRJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1Background_Aspect_1Background_1Create_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fBackground
 * Method:    Color
 * Signature: ()LSampleHLRJni/Quantity_Color;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1Background_Color
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fBackground
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1Background_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_Aspect_0005fBackground
 * Method:    SetColor
 * Signature: (LSampleHLRJni/Quantity_Color;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1Background_SetColor
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
