/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Viewer_0005fView */

#ifndef _Included_SampleHLRJni_Viewer_0005fView
#define _Included_SampleHLRJni_Viewer_0005fView
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
