/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_SampleHLRPackage */

#ifndef _Included_SampleHLRJni_SampleHLRPackage
#define _Included_SampleHLRJni_SampleHLRPackage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    Apply
 * Signature: (LSampleHLRJni/ISession2D_InteractiveContext;I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_Apply
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    CreateView2d
 * Signature: (LSampleHLRJni/V2d_Viewer;II)LSampleHLRJni/V2d_View;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_SampleHLRPackage_CreateView2d
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    CreateViewer2d
 * Signature: (Ljava/lang/String;)LSampleHLRJni/V2d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_SampleHLRPackage_CreateViewer2d
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    CreateViewer3d
 * Signature: (Ljava/lang/String;)LSampleHLRJni/V3d_Viewer;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_SampleHLRPackage_CreateViewer3d
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    DisplayTrihedron
 * Signature: (LSampleHLRJni/AIS_InteractiveContext;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_DisplayTrihedron
  (JNIEnv *, jclass, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    GetShapes
 * Signature: (LSampleHLRJni/AIS_InteractiveContext;LSampleHLRJni/AIS_InteractiveContext;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_SampleHLRPackage_GetShapes
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    InitMaps
 * Signature: (LSampleHLRJni/V2d_Viewer;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_InitMaps
  (JNIEnv *, jclass, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    ReadBRep
 * Signature: (Ljcas/Standard_CString;LSampleHLRJni/AIS_InteractiveContext;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_SampleHLRPackage_ReadBRep
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    SampleHLRPackage_SaveImage_1
 * Signature: (Ljcas/Standard_CString;Ljcas/Standard_CString;LSampleHLRJni/V3d_View;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_SampleHLRPackage_SampleHLRPackage_1SaveImage_11
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    SampleHLRPackage_SaveImage_2
 * Signature: (Ljcas/Standard_CString;Ljcas/Standard_CString;LSampleHLRJni/V2d_View;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_SampleHLRPackage_SampleHLRPackage_1SaveImage_12
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    SaveBRep
 * Signature: (Ljcas/Standard_CString;LSampleHLRJni/AIS_InteractiveContext;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_SampleHLRPackage_SaveBRep
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    SetNbIsos
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_SetNbIsos
  (JNIEnv *, jclass, jint);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    SetWindow3d
 * Signature: (LSampleHLRJni/V3d_View;II)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_SetWindow3d
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     SampleHLRJni_SampleHLRPackage
 * Method:    UpdateProjector
 * Signature: (LSampleHLRJni/V3d_View;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_SampleHLRPackage_UpdateProjector
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
