/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_TCollection_0005fExtendedString */

#ifndef _Included_SampleHLRJni_TCollection_0005fExtendedString
#define _Included_SampleHLRJni_TCollection_0005fExtendedString
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_TCollection_0005fExtendedString
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TCollection_1ExtendedString_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
