/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_Graphic3d_0005fGraphicDriver */

#ifndef _Included_SampleViewer3DJni_Graphic3d_0005fGraphicDriver
#define _Included_SampleViewer3DJni_Graphic3d_0005fGraphicDriver
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    BeginPolygon2d
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_BeginPolygon2d
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    BeginPolyline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_BeginPolyline
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    BeginPolyline2d
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_BeginPolyline2d
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    CreateTexture
 * Signature: (SLSampleViewer3DJni/AlienImage_AlienImage;Ljcas/Standard_CString;LSampleViewer3DJni/TColStd_HArray1OfReal;)I
 */
JNIEXPORT jint JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_CreateTexture
  (JNIEnv *, jobject, jshort, jobject, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    DestroyTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_DestroyTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Edge
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Edge
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    End
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_End
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndAddMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndAddMode
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndImmediatMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndImmediatMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndLayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndLayer
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndPolygon2d
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndPolygon2d
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndPolyline
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndPolyline
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    EndPolyline2d
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_EndPolyline2d
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Begin_1
 * Signature: (Ljcas/Standard_CString;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Begin_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Create_0
 * Signature: (Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Create_10
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Draw_1
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Draw_11
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Draw_2
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Draw_12
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Move_1
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Move_11
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Move_2
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Move_12
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Graphic3d_GraphicDriver_Text_5
 * Signature: (Ljcas/Standard_CString;FFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Graphic3d_1GraphicDriver_1Text_15
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    InitPick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_InitPick
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    InquireLightLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_InquireLightLimit
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    InquirePlaneLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_InquirePlaneLimit
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    InquireTextureAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_InquireTextureAvailable
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    InquireViewLimit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_InquireViewLimit
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintBoolean
 * Signature: (Ljcas/Standard_CString;Z)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintBoolean
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintFunction
 * Signature: (Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintFunction
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintIResult
 * Signature: (Ljcas/Standard_CString;I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintIResult
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintInteger
 * Signature: (Ljcas/Standard_CString;I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintInteger
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintMatrix
 * Signature: (Ljcas/Standard_CString;LSampleViewer3DJni/TColStd_Array2OfReal;)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintMatrix
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintShortReal
 * Signature: (Ljcas/Standard_CString;F)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintShortReal
  (JNIEnv *, jobject, jobject, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    PrintString
 * Signature: (Ljcas/Standard_CString;Ljcas/Standard_CString;)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_PrintString
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Rectangle
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Rectangle
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetColor
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetLineAttributes
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetLineAttributes
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetLineColor
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetLineColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetLineType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetLineType
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetMinMax
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetMinMax
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetTextAttributes
 * Signature: (IIFFF)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetTextAttributes
  (JNIEnv *, jobject, jchar*, jint, jfloat, jfloat, jfloat);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    SetTrace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_SetTrace
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    TextSize
 * Signature: (Ljcas/Standard_CString;FLjcas/Standard_ShortReal;Ljcas/Standard_ShortReal;Ljcas/Standard_ShortReal;)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_TextSize
  (JNIEnv *, jobject, jobject, jfloat, jobject, jobject, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Trace
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Trace
  (JNIEnv *, jobject);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    Transform
 * Signature: (LSampleViewer3DJni/TColStd_Array2OfReal;S)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_Transform
  (JNIEnv *, jobject, jobject, jshort);

/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fGraphicDriver
 * Method:    ZBufferTriedronSetup
 * Signature: (SSSDDI)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1GraphicDriver_ZBufferTriedronSetup
  (JNIEnv *, jobject, jshort, jshort, jshort, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
