/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fFontMap */

#ifndef _Included_SampleHLRJni_Aspect_0005fFontMap
#define _Included_SampleHLRJni_Aspect_0005fFontMap
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Aspect_FontMap_AddEntry_1
 * Signature: (LSampleHLRJni/Aspect_FontMapEntry;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMap_Aspect_1FontMap_1AddEntry_11
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Aspect_FontMap_AddEntry_2
 * Signature: (LSampleHLRJni/Aspect_FontStyle;)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1FontMap_Aspect_1FontMap_1AddEntry_12
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Aspect_FontMap_Create_0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMap_Aspect_1FontMap_1Create_10
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Dump
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1FontMap_Dump
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Entry
 * Signature: (I)LSampleHLRJni/Aspect_FontMapEntry;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1FontMap_Entry
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Index
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1FontMap_Index
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_Aspect_0005fFontMap
 * Method:    Size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1FontMap_Size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
