/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleAISBasicJni_AIS_0005fInteractiveContext */

#ifndef _Included_SampleAISBasicJni_AIS_0005fInteractiveContext
#define _Included_SampleAISBasicJni_AIS_0005fInteractiveContext
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
#ifdef __cplusplus
}
#endif
#endif
