/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleViewer3DJni_Graphic3d_0005fArray2OfVertexN */

#ifndef _Included_SampleViewer3DJni_Graphic3d_0005fArray2OfVertexN
#define _Included_SampleViewer3DJni_Graphic3d_0005fArray2OfVertexN
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleViewer3DJni_Graphic3d_0005fArray2OfVertexN
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleViewer3DJni_Graphic3d_1Array2OfVertexN_FinalizeValue
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
