/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_Aspect_0005fMarkerStyle */

#ifndef _Included_SampleHLRJni_Aspect_0005fMarkerStyle
#define _Included_SampleHLRJni_Aspect_0005fMarkerStyle
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Aspect_MarkerStyle_Create_1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Aspect_1MarkerStyle_1Create_11
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Aspect_MarkerStyle_Create_2
 * Signature: (S)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Aspect_1MarkerStyle_1Create_12
  (JNIEnv *, jobject, jshort);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Aspect_MarkerStyle_Create_3
 * Signature: (LSampleHLRJni/TColStd_Array1OfReal;LSampleHLRJni/TColStd_Array1OfReal;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Aspect_1MarkerStyle_1Create_13
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Aspect_MarkerStyle_Create_4
 * Signature: (LSampleHLRJni/TColStd_Array1OfReal;LSampleHLRJni/TColStd_Array1OfReal;LSampleHLRJni/TColStd_Array1OfBoolean;)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Aspect_1MarkerStyle_1Create_14
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Assign
 * Signature: (LSampleHLRJni/Aspect_MarkerStyle;)LSampleHLRJni/Aspect_MarkerStyle;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    IsEqual
 * Signature: (LSampleHLRJni/Aspect_MarkerStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_IsEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    IsNotEqual
 * Signature: (LSampleHLRJni/Aspect_MarkerStyle;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_IsNotEqual
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Length
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    SValues
 * Signature: ()LSampleHLRJni/TColStd_Array1OfBoolean;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_SValues
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Type
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Type
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    Values
 * Signature: (ILjcas/Standard_Real;Ljcas/Standard_Real;)Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_Values
  (JNIEnv *, jobject, jint, jobject, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    XValues
 * Signature: ()LSampleHLRJni/TShort_Array1OfShortReal;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_XValues
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_Aspect_0005fMarkerStyle
 * Method:    YValues
 * Signature: ()LSampleHLRJni/TShort_Array1OfShortReal;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_Aspect_1MarkerStyle_YValues
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
