/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SampleHLRJni_TColQuantity_0005fArray1OfLength */

#ifndef _Included_SampleHLRJni_TColQuantity_0005fArray1OfLength
#define _Included_SampleHLRJni_TColQuantity_0005fArray1OfLength
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: myCasLock */
/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Assign
 * Signature: (LSampleHLRJni/TColQuantity_Array1OfLength;)LSampleHLRJni/TColQuantity_Array1OfLength;
 */
JNIEXPORT jobject JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Assign
  (JNIEnv *, jobject, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    ChangeValue
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_ChangeValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Destroy
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    FinalizeValue
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_FinalizeValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Init
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Init
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    IsAllocated
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_IsAllocated
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Length
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Lower
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Lower
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    SetValue
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_SetValue
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    TColQuantity_Array1OfLength_Create_1
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_TColQuantity_1Array1OfLength_1Create_11
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    TColQuantity_Array1OfLength_Create_2
 * Signature: (DII)V
 */
JNIEXPORT void JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_TColQuantity_1Array1OfLength_1Create_12
  (JNIEnv *, jobject, jdouble, jint, jint);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Upper
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Upper
  (JNIEnv *, jobject);

/*
 * Class:     SampleHLRJni_TColQuantity_0005fArray1OfLength
 * Method:    Value
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_SampleHLRJni_TColQuantity_1Array1OfLength_Value
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
