// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _Handle_OCAFSample_Driver_HeaderFile
#define _Handle_OCAFSample_Driver_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_TFunction_Driver_HeaderFile
#include <Handle_TFunction_Driver.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(TFunction_Driver);
class OCAFSample_Driver;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(OCAFSample_Driver);

class Handle(OCAFSample_Driver) : public Handle(TFunction_Driver) {
  public:
    inline void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    inline void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    inline void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
//    inline void  operator delete(void *anAddress, size_t size) 
//      { 
//        if (anAddress) Standard::Free((Standard_Address&)anAddress,size); 
//      }
    Handle(OCAFSample_Driver)():Handle(TFunction_Driver)() {} 
    Handle(OCAFSample_Driver)(const Handle(OCAFSample_Driver)& aHandle) : Handle(TFunction_Driver)(aHandle) 
     {
     }

    Handle(OCAFSample_Driver)(const OCAFSample_Driver* anItem) : Handle(TFunction_Driver)((TFunction_Driver *)anItem) 
     {
     }

    Handle(OCAFSample_Driver)& operator=(const Handle(OCAFSample_Driver)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(OCAFSample_Driver)& operator=(const OCAFSample_Driver* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    OCAFSample_Driver* operator->() 
     {
      return (OCAFSample_Driver *)ControlAccess();
     }

    OCAFSample_Driver* operator->() const 
     {
      return (OCAFSample_Driver *)ControlAccess();
     }

   Standard_EXPORT ~Handle(OCAFSample_Driver)();
 
   Standard_EXPORT static const Handle(OCAFSample_Driver) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
