

#ifndef TFunction_DoubleMapIteratorOfDoubleMapOfIntegerLabel_HeaderFile
#define TFunction_DoubleMapIteratorOfDoubleMapOfIntegerLabel_HeaderFile

#include <TFunction_DoubleMapOfIntegerLabel.hxx>

#endif
