set(OCCT_BRepGraph_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepGraph_FILES
  BRepGraph.cxx
  BRepGraph.hxx
  BRepGraph_Cache.cxx
  BRepGraph_Cache.hxx
  BRepGraph_CacheChart.cxx
  BRepGraph_CacheChart.hxx
  BRepGraph_CacheDerivedState.cxx
  BRepGraph_CacheDerivedState.hxx
  BRepGraph_CacheIterator.hxx
  BRepGraph_CacheRegistry.cxx
  BRepGraph_CacheRegistry.hxx
  BRepGraph_EditorView.cxx
  BRepGraph_EditorView.hxx
  BRepGraph_EditorView_Mut.cxx
  BRepGraph_EditorView_Setters.cxx
  BRepGraph_DefsIterator.hxx
  BRepGraph_FilteredIterator.hxx
  BRepGraph_ChildIterator.cxx
  BRepGraph_ChildIterator.hxx
  BRepGraph_ChildExplorer.cxx
  BRepGraph_ChildExplorer.hxx
  BRepGraph_Iterator.hxx
  BRepGraph_ItemId.hxx
  BRepGraph_ItemUID.hxx
  BRepGraph_ParentExplorer.cxx
  BRepGraph_ParentExplorer.hxx
  BRepGraph_ParentIterator.cxx
  BRepGraph_ParentIterator.hxx
  BRepGraph_Data.hxx
  BRepGraph_TopoView.cxx
  BRepGraph_TopoView.hxx
  BRepGraph_LayerHistory.cxx
  BRepGraph_LayerHistory.hxx
  BRepGraph_Layer.cxx
  BRepGraph_Layer.hxx
  BRepGraph_LayerParametric.cxx
  BRepGraph_LayerParametric.hxx
  BRepGraph_LayerDeferred.cxx
  BRepGraph_LayerDeferred.hxx
  BRepGraph_LayerIterator.hxx
  BRepGraph_LayerLock.cxx
  BRepGraph_LayerLock.hxx
  BRepGraph_LayerRegistry.cxx
  BRepGraph_LayerRegistry.hxx
  BRepGraph_LayerSupplement.cxx
  BRepGraph_LayerSupplement.hxx
  BRepGraph_LayerSupplementBase.cxx
  BRepGraph_LayerSupplementBase.hxx
  BRepGraph_LayerSupplementRegistry.cxx
  BRepGraph_LayerSupplementRegistry.hxx
  BRepGraph_DeferredScope.hxx
  BRepGraph_CacheMesh.cxx
  BRepGraph_CacheMesh.hxx
  BRepGraph_MeshView.cxx
  BRepGraph_MeshView.hxx
  BRepGraph_MutGuard.hxx
  BRepGraph_NodeId.hxx
  BRepGraph_ParallelPolicy.cxx
  BRepGraph_ParallelPolicy.hxx
  BRepGraph_RefId.hxx
  BRepGraph_RefUID.hxx
  BRepGraph_RelatedIterator.cxx
  BRepGraph_RelatedIterator.hxx
  BRepGraph_ReverseIterator.hxx
  BRepGraph_RefsIterator.hxx
  BRepGraph_RefsView.cxx
  BRepGraph_RefsView.hxx
  BRepGraph_ShapesView.cxx
  BRepGraph_ShapesView.hxx
  BRepGraph_SupplementsView.cxx
  BRepGraph_SupplementsView.hxx
  BRepGraph_Tool.cxx
  BRepGraph_Tool.hxx
  BRepGraph_UsagePath.cxx
  BRepGraph_UsagePath.hxx
  BRepGraph_UID.hxx
  BRepGraph_UIDsView.cxx
  BRepGraph_ItemStamp.cxx
  BRepGraph_ItemStamp.hxx
  BRepGraph_UIDsView.hxx
  BRepGraph_Deduplicate.cxx
  BRepGraph_Deduplicate.hxx
  BRepGraph_Compact.hxx
  BRepGraph_Compact.cxx
  BRepGraph_Copy.hxx
  BRepGraph_Copy.cxx
  BRepGraph_CopyRemap.hxx
  BRepGraph_CopyRemap.cxx
  BRepGraph_Replace.hxx
  BRepGraph_Replace.cxx
  BRepGraph_Transform.hxx
  BRepGraph_Transform.cxx
  BRepGraph_Validate.hxx
  BRepGraph_Validate.cxx
  BRepGraph_RevisionDiff.hxx
  BRepGraph_Transaction.hxx
  BRepGraph_Transaction.cxx
  BRepGraph_RevisionComponent.hxx
  BRepGraph_RevisionComponent.cxx
  BRepGraph_RevisionStatus.hxx
  BRepGraph_RevisionHash.hxx
  BRepGraph_RevisionHash.cxx
  BRepGraph_RevisionMerkle.hxx
  BRepGraph_RevisionMerkle.cxx
  BRepGraph_Revision.hxx
  BRepGraph_Revision.cxx
  BRepGraph_RevisionDiff.cxx
)
