set(OCCT_BRepGraph_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepGraph_FILES
  BRepGraph.cxx
  BRepGraph.hxx
  BRepGraph_Analyze.cxx
  BRepGraph_Analyze.hxx
  BRepGraph_AttrsView.cxx
  BRepGraph_AttrsView.hxx
  BRepGraph_Builder.cxx
  BRepGraph_Builder.hxx
  BRepGraph_BuilderView.cxx
  BRepGraph_BuilderView.hxx
  BRepGraph_Data.hxx
  BRepGraph_TopoView.cxx
  BRepGraph_TopoView.hxx
  BRepGraph_Explorer.cxx
  BRepGraph_Explorer.hxx
  BRepGraph_History.cxx
  BRepGraph_History.hxx
  BRepGraph_HistoryRecord.hxx
  BRepGraph_Iterator.hxx
  BRepGraph_Layer.cxx
  BRepGraph_Layer.hxx
  BRepGraph_MutationGuard.hxx
  BRepGraph_MutRef.hxx
  BRepGraph_Mutator.cxx
  BRepGraph_Mutator.hxx
  BRepGraph_NameLayer.cxx
  BRepGraph_NameLayer.hxx
  BRepGraph_NodeCache.hxx
  BRepGraph_NodeId.hxx
  BRepGraph_PathView.cxx
  BRepGraph_PathView.hxx
  BRepGraph_RepId.hxx
  BRepGraph_ShapesView.cxx
  BRepGraph_ShapesView.hxx
  BRepGraph_SubGraph.hxx
  BRepGraph_TopologyPath.hxx
  BRepGraph_Tool.cxx
  BRepGraph_Tool.hxx
  BRepGraph_TopoNode.hxx
  BRepGraph_UID.hxx
  BRepGraph_UIDsView.cxx
  BRepGraph_UIDsView.hxx
  BRepGraph_UserAttribute.hxx
)
