set(OCCT_BRepGraph_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_BRepGraph_FILES
  BRepGraph.cxx
  BRepGraph.hxx
  BRepGraph_Analyze.cxx
  BRepGraph_Analyze.hxx
  BRepGraph_AttrRegistry.hxx
  BRepGraph_Builder.cxx
  BRepGraph_Builder.hxx
  BRepGraph_CachedValue.hxx
  BRepGraph_Data.hxx
  BRepGraph_GeomNode.hxx
  BRepGraph_History.cxx
  BRepGraph_History.hxx
  BRepGraph_HistoryRecord.hxx
  BRepGraph_Iterator.hxx
  BRepGraph_Mutator.cxx
  BRepGraph_Mutator.hxx
  BRepGraph_NodeCache.hxx
  BRepGraph_NodeId.hxx
  BRepGraph_Reconstruct.cxx
  BRepGraph_Reconstruct.hxx
  BRepGraph_RelEdge.hxx
  BRepGraph_SubGraph.hxx
  BRepGraph_TopoNode.hxx
  BRepGraph_UID.hxx
  BRepGraph_UsageId.hxx
  BRepGraph_UserAttribute.hxx
)
