# Test source files for TKMath
set(OCCT_TKMath_GTests_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TKMath_GTests_FILES
  Bnd_B2_Test.cxx
  Bnd_B3_Test.cxx
  Bnd_BoundSortBox_Test.cxx
  Bnd_Box_Test.cxx
  Bnd_OBB_Test.cxx
  BSplCLib_Cache_Test.cxx
  BSplSLib_Cache_Test.cxx
  BVH_BinnedBuilder_Test.cxx
  BVH_Box_Test.cxx
  BVH_BuildQueue_Test.cxx
  BVH_LinearBuilder_Test.cxx
  BVH_QuickSorter_Test.cxx
  BVH_RadixSorter_Test.cxx
  BVH_Ray_Test.cxx
  BVH_SpatialMedianBuilder_Test.cxx
  BVH_SweepPlaneBuilder_Test.cxx
  BVH_Tools_Test.cxx
  BVH_Traverse_Test.cxx
  BVH_Triangulation_Test.cxx
  BVH_Tree_Test.cxx
  CSLib_Test.cxx
  ElCLib_Test.cxx
  gp_Ax3_Test.cxx
  gp_Mat_Test.cxx
  gp_Trsf_Test.cxx
  math_BFGS_Test.cxx
  math_BissecNewton_Test.cxx
  math_BracketMinimum_Test.cxx
  math_BracketedRoot_Test.cxx
  math_Crout_Test.cxx
  math_BrentMinimum_Test.cxx
  math_ComputeKronrodPointsAndWeights_Test.cxx
  math_DirectPolynomialRoots_Test.cxx
  math_DoubleTab_Test.cxx
  math_EigenValuesSearcher_Test.cxx
  math_FRPR_Test.cxx
  math_FunctionAllRoots_Test.cxx
  math_FunctionRoot_Test.cxx
  math_FunctionRoots_Test.cxx
  math_FunctionSetRoot_Test.cxx
  math_Gauss_Test.cxx
  math_GaussLeastSquare_Test.cxx
  math_GlobOptMin_Test.cxx
  math_Householder_Test.cxx
  math_Integration_Test.cxx
  math_Jacobi_Test.cxx
  math_Matrix_Test.cxx
  math_NewtonFunctionRoot_Test.cxx
  math_NewtonFunctionSetRoot_Test.cxx
  math_NewtonMinimum_Test.cxx
  math_Powell_Test.cxx
  math_PSO_Test.cxx
  math_SVD_Test.cxx
  math_TrigonometricFunctionRoots_Test.cxx
  math_Uzawa_Test.cxx
  math_Vector_Test.cxx
  PLib_Test.cxx
  PLib_JacobiPolynomial_Test.cxx
  PLib_HermitJacobi_Test.cxx
)
