// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.

#ifndef _Handle_Sphere_BasicShape_HeaderFile
#define _Handle_Sphere_BasicShape_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif

#ifndef _Handle_AIS_Shape_HeaderFile
#include <Handle_AIS_Shape.hxx>
#endif

class Standard_Transient;
class Handle_Standard_Type;
class Handle(AIS_Shape);
class Sphere_BasicShape;
Standard_EXPORT Handle_Standard_Type& STANDARD_TYPE(Sphere_BasicShape);

class Handle(Sphere_BasicShape) : public Handle(AIS_Shape) {
  public:
    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
    Handle(Sphere_BasicShape)():Handle(AIS_Shape)() {} 
    Handle(Sphere_BasicShape)(const Handle(Sphere_BasicShape)& aHandle) : Handle(AIS_Shape)(aHandle) 
     {
     }

    Handle(Sphere_BasicShape)(const Sphere_BasicShape* anItem) : Handle(AIS_Shape)((AIS_Shape *)anItem) 
     {
     }

    Handle(Sphere_BasicShape)& operator=(const Handle(Sphere_BasicShape)& aHandle)
     {
      Assign(aHandle.Access());
      return *this;
     }

    Handle(Sphere_BasicShape)& operator=(const Sphere_BasicShape* anItem)
     {
      Assign((Standard_Transient *)anItem);
      return *this;
     }

    Sphere_BasicShape* operator->() 
     {
      return (Sphere_BasicShape *)ControlAccess();
     }

    Sphere_BasicShape* operator->() const 
     {
      return (Sphere_BasicShape *)ControlAccess();
     }

   Standard_EXPORT ~Handle(Sphere_BasicShape)();
 
   Standard_EXPORT static const Handle(Sphere_BasicShape) DownCast(const Handle(Standard_Transient)& AnObject);
};
#endif
