// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _Sphere_BasicShape_HeaderFile
#define _Sphere_BasicShape_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_Sphere_BasicShape_HeaderFile
#include <Handle_Sphere_BasicShape.hxx>
#endif

#include <Standard_Real.hxx>
#include <Standard_Boolean.hxx>
#include <AIS_Shape.hxx>
class TopoDS_Shape;
class gp_Pnt;


class Sphere_BasicShape : public AIS_Shape {

public:

    void* operator new(size_t,void* anAddress) 
      {
        return anAddress;
      }
    void* operator new(size_t size) 
      { 
        return Standard::Allocate(size); 
      }
    void  operator delete(void *anAddress) 
      { 
        if (anAddress) Standard::Free((Standard_Address&)anAddress); 
      }
 // Methods PUBLIC
 // 
Standard_EXPORT Sphere_BasicShape(const TopoDS_Shape& aShape,const Standard_Real aDeflection,const Standard_Boolean hasVNormals,const Standard_Boolean hasVColors,const Standard_Boolean hasVTexels);
Standard_EXPORT   void SetPosition(const gp_Pnt& aPosition) ;
Standard_EXPORT   void SetVNormals(const Standard_Boolean aFlag) ;
Standard_EXPORT   void SetVColors(const Standard_Boolean aFlag) ;
Standard_EXPORT   void SetVTexels(const Standard_Boolean aFlag) ;
Standard_EXPORT   void SetDeflection(const Standard_Real aValue) ;
Standard_EXPORT   gp_Pnt Position() const;
Standard_EXPORT   Standard_Boolean VNormalsFlag() const;
Standard_EXPORT   Standard_Boolean VColorsFlag() const;
Standard_EXPORT   Standard_Boolean VTexelsFlag() const;
Standard_EXPORT   Standard_Real Deflection() const;
Standard_EXPORT ~Sphere_BasicShape();




 // Type management
 //
 Standard_EXPORT friend Handle_Standard_Type& Sphere_BasicShape_Type_();
 Standard_EXPORT const Handle_Standard_Type& DynamicType() const;
 Standard_EXPORT Standard_Boolean	       IsKind(const Handle(Standard_Type)&) const;

protected:

 // Methods PROTECTED
 // 


 // Fields PROTECTED
 //
Standard_Real myDeflection;
Standard_Boolean myVNormalsFlag;
Standard_Boolean myVColorsFlag;
Standard_Boolean myVTexelsFlag;


private: 

 // Methods PRIVATE
 // 


 // Fields PRIVATE
 //


};





// other Inline functions and methods (like "C++: function call" methods)
//


#endif
