# Source files for DsgPrs package
set(OCCT_DsgPrs_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_DsgPrs_FILES
  DsgPrs.cxx
  DsgPrs.hxx
  DsgPrs_ArrowSide.hxx
  DsgPrs_Chamf2dPresentation.cxx
  DsgPrs_Chamf2dPresentation.hxx
  DsgPrs_ConcentricPresentation.cxx
  DsgPrs_ConcentricPresentation.hxx
  DsgPrs_EllipseRadiusPresentation.cxx
  DsgPrs_EllipseRadiusPresentation.hxx
  DsgPrs_EqualDistancePresentation.cxx
  DsgPrs_EqualDistancePresentation.hxx
  DsgPrs_EqualRadiusPresentation.cxx
  DsgPrs_EqualRadiusPresentation.hxx
  DsgPrs_FixPresentation.cxx
  DsgPrs_FixPresentation.hxx
  DsgPrs_IdenticPresentation.cxx
  DsgPrs_IdenticPresentation.hxx
  DsgPrs_LengthPresentation.cxx
  DsgPrs_LengthPresentation.hxx
  DsgPrs_MidPointPresentation.cxx
  DsgPrs_MidPointPresentation.hxx
  DsgPrs_OffsetPresentation.cxx
  DsgPrs_OffsetPresentation.hxx
  DsgPrs_PerpenPresentation.cxx
  DsgPrs_PerpenPresentation.hxx
  DsgPrs_ShadedPlanePresentation.cxx
  DsgPrs_ShadedPlanePresentation.hxx
  DsgPrs_SymmetricPresentation.cxx
  DsgPrs_SymmetricPresentation.hxx
  DsgPrs_TangentPresentation.cxx
  DsgPrs_TangentPresentation.hxx
  DsgPrs_XYZAxisPresentation.cxx
  DsgPrs_XYZAxisPresentation.hxx
  DsgPrs_XYZPlanePresentation.cxx
  DsgPrs_XYZPlanePresentation.hxx
)
