# Source files for StdPrs package
set(OCCT_StdPrs_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_StdPrs_FILES
  StdPrs_BRepFont.cxx
  StdPrs_BRepFont.hxx
  StdPrs_BRepTextBuilder.cxx
  StdPrs_BRepTextBuilder.hxx
  StdPrs_Curve.cxx
  StdPrs_Curve.hxx
  StdPrs_DeflectionCurve.cxx
  StdPrs_DeflectionCurve.hxx
  StdPrs_HLRPolyShape.cxx
  StdPrs_HLRPolyShape.hxx
  StdPrs_HLRShape.cxx
  StdPrs_HLRShape.hxx
  StdPrs_HLRShapeI.cxx
  StdPrs_HLRShapeI.hxx
  StdPrs_HLRToolShape.cxx
  StdPrs_HLRToolShape.hxx
  StdPrs_Isolines.cxx
  StdPrs_Isolines.hxx
  StdPrs_Plane.cxx
  StdPrs_Plane.hxx
  StdPrs_Point.hxx
  StdPrs_ShadedShape.cxx
  StdPrs_ShadedShape.hxx
  StdPrs_ShapeTool.cxx
  StdPrs_ShapeTool.hxx
  StdPrs_ToolPoint.cxx
  StdPrs_ToolPoint.hxx
  StdPrs_ToolRFace.cxx
  StdPrs_ToolRFace.hxx
  StdPrs_ToolTriangulatedShape.cxx
  StdPrs_ToolTriangulatedShape.hxx
  StdPrs_Volume.hxx
  StdPrs_WFShape.cxx
  StdPrs_WFShape.hxx
)
