

#ifndef TopOpeBRepTool_DataMapIteratorOfDataMapOfOrientedShapeC2DF_HeaderFile
#define TopOpeBRepTool_DataMapIteratorOfDataMapOfOrientedShapeC2DF_HeaderFile

#include <TopOpeBRepTool_DataMapOfOrientedShapeC2DF.hxx>

#endif
