#include <StepVisual_MechanicalDesignGeometricPresentationRepresentation.ixx>


StepVisual_MechanicalDesignGeometricPresentationRepresentation::StepVisual_MechanicalDesignGeometricPresentationRepresentation ()  {}

