# Source files for RWStepElement package
set(OCCT_RWStepElement_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_RWStepElement_FILES
  RWStepElement_RWAnalysisItemWithinRepresentation.cxx
  RWStepElement_RWAnalysisItemWithinRepresentation.pxx
  RWStepElement_RWCurve3dElementDescriptor.cxx
  RWStepElement_RWCurve3dElementDescriptor.pxx
  RWStepElement_RWCurveElementEndReleasePacket.cxx
  RWStepElement_RWCurveElementEndReleasePacket.pxx
  RWStepElement_RWCurveElementSectionDefinition.cxx
  RWStepElement_RWCurveElementSectionDefinition.pxx
  RWStepElement_RWCurveElementSectionDerivedDefinitions.cxx
  RWStepElement_RWCurveElementSectionDerivedDefinitions.pxx
  RWStepElement_RWElementDescriptor.cxx
  RWStepElement_RWElementDescriptor.pxx
  RWStepElement_RWElementMaterial.cxx
  RWStepElement_RWElementMaterial.pxx
  RWStepElement_RWSurface3dElementDescriptor.cxx
  RWStepElement_RWSurface3dElementDescriptor.pxx
  RWStepElement_RWSurfaceElementProperty.cxx
  RWStepElement_RWSurfaceElementProperty.pxx
  RWStepElement_RWSurfaceSection.cxx
  RWStepElement_RWSurfaceSection.pxx
  RWStepElement_RWSurfaceSectionField.cxx
  RWStepElement_RWSurfaceSectionField.pxx
  RWStepElement_RWSurfaceSectionFieldConstant.cxx
  RWStepElement_RWSurfaceSectionFieldConstant.pxx
  RWStepElement_RWSurfaceSectionFieldVarying.cxx
  RWStepElement_RWSurfaceSectionFieldVarying.pxx
  RWStepElement_RWUniformSurfaceSection.cxx
  RWStepElement_RWUniformSurfaceSection.pxx
  RWStepElement_RWVolume3dElementDescriptor.cxx
  RWStepElement_RWVolume3dElementDescriptor.pxx
)
