

#ifndef MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger_HeaderFile
#define MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger_HeaderFile

#include <MeshVS_DataMapOfTwoColorsMapOfInteger.hxx>

#endif
