# External dependencies for TKService
set(OCCT_TKService_EXTERNAL_LIBS
  TKernel
  TKMath
  CSF_user32
  CSF_advapi32
  CSF_OpenVR
  CSF_advapi32
  CSF_user32
  CSF_XwLibs
  CSF_wayland
  CSF_fontconfig
  CSF_objc
  CSF_Appkit
  CSF_IOKit
  CSF_FreeImagePlus
  CSF_FREETYPE
  CSF_FFmpeg
  CSF_winmm
)
