#qt

#looking for 3RDPARTY_QT_DIR variable used later in qt5_macro.cmake
if (${USE_QT4})
  SET(CSF_QtCore "QtCore")
  THIRDPARTY_PRODUCT("QT" "" "CSF_QtCore" "d")
else()
  SET(CSF_Qt5Core "Qt5Core")
  THIRDPARTY_PRODUCT("QT" "" "CSF_Qt5Core" "d")
endif()

list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED "3RDPARTY_QT_INCLUDE_DIR")
list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED "3RDPARTY_QT_LIBRARY_DIR")
list (REMOVE_ITEM 3RDPARTY_NOT_INCLUDED "3RDPARTY_QT_DLL_DIR")

UNSET (${3RDPARTY_QT_DLL} CACHE)
UNSET (${3RDPARTY_QT_DLL_DIR} CACHE)
UNSET (${3RDPARTY_QT_INCLUDE_DIR} CACHE)
UNSET (${3RDPARTY_QT_LIBRARY} CACHE)
UNSET (${3RDPARTY_QT_LIBRARY_DIR} CACHE)

set (USED_3RDPARTY_QT_DIR "${3RDPARTY_QT_DIR}")
