# Test source files for TKG2d
set(OCCT_TKG2d_GTests_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_TKG2d_GTests_FILES
  Adaptor2d_Line2d_Test.cxx
  Adaptor2d_OffsetCurve_Test.cxx
  Geom2d_AxisPlacement_Test.cxx
  Geom2d_BSplineCurve_Test.cxx
  Geom2d_BezierCurve_Test.cxx
  Geom2d_CartesianPoint_Test.cxx
  Geom2d_Circle_Test.cxx
  Geom2d_CurveEval_Test.cxx
  Geom2d_Direction_Test.cxx
  Geom2d_Ellipse_Test.cxx
  Geom2d_Hyperbola_Test.cxx
  Geom2d_Line_Test.cxx
  Geom2d_OffsetCurve_Test.cxx
  Geom2d_Parabola_Test.cxx
  Geom2d_Transformation_Test.cxx
  Geom2d_TrimmedCurve_Test.cxx
  Geom2d_VectorWithMagnitude_Test.cxx
  Geom2dAdaptor_Curve_Test.cxx
  Geom2dAPI_InterCurveCurve_Test.cxx
  Geom2dEval_ArchimedeanSpiralCurve_Test.cxx
  Geom2dEval_AHTBezierCurve_Test.cxx
  Geom2dEval_CircleInvoluteCurve_Test.cxx
  Geom2dEval_LogarithmicSpiralCurve_Test.cxx
  Geom2dEval_SineWaveCurve_Test.cxx
  Geom2dEval_TBezierCurve_Test.cxx
  Geom2dGcc_Circ2d2TanOn_Test.cxx
  Geom2dGcc_Circ2d2TanRad_Test.cxx
  Geom2dProp_BezierCurve_Test.cxx
  Geom2dProp_BSplineCurve_Test.cxx
  Geom2dProp_Circle_Test.cxx
  Geom2dProp_Ellipse_Test.cxx
  Geom2dProp_Hyperbola_Test.cxx
  Geom2dProp_Line_Test.cxx
  Geom2dProp_OffsetCurve_Test.cxx
  Geom2dProp_OtherCurve_Test.cxx
  Geom2dProp_Parabola_Test.cxx
  Geom2dProp_Test.cxx
  Geom2dProp_VsCLProps2d_Test.cxx
  Geom2dProp_VsLProp_Test.cxx
  Geom2dGridEval_BezierCurve_Test.cxx
  Geom2dGridEval_Curve_Test.cxx
  Geom2dGridEval_Ellipse_Test.cxx
  Geom2dGridEval_Hyperbola_Test.cxx
  Geom2dGridEval_Parabola_Test.cxx
  Geom2dHash_CurveHasher_Test.cxx
  Geom2dLProp_CLProps2d_Test.cxx
  Geom2dLProp_CurAndInf2d_Test.cxx
  LProp_CurAndInf_Test.cxx
)
