

#ifndef SelectMgr_DataMapIteratorOfDataMapOfObjectSelectors_HeaderFile
#define SelectMgr_DataMapIteratorOfDataMapOfObjectSelectors_HeaderFile

#include <SelectMgr_DataMapOfObjectSelectors.hxx>

#endif
