!!!!!!!!!! ----- Messages file for BOPAlgo package --------- !!!!!!!!!
!  Keyword is name of corresponding alert (error or warning) class

! Special key used to check that messages are loaded; see BOPAlgo_Options.cxx
.BOPAlgo_LOAD_CHECKER
N/A

.BOPAlgo_AlertBOPIsNotSet
Error: The type of Boolean Operation is not set

.BOPAlgo_AlertBOPNotAllowed
Error: Boolean operation of the given type is not allowed on the given inputs

.BOPAlgo_AlertSolidBuilderFailed
Error: Building Fused solid has failed

.BOPAlgo_AlertTooFewArguments
Error: There are no enough arguments to perform the operation

.BOPAlgo_AlertMultipleArguments
Error: More than one argument is provided

.BOPAlgo_AlertNoFiller
Error: The Pave Filler (the intersection tool) has not been created

.BOPAlgo_AlertIntersectionFailed
Error: The intersection of the arguments has failed

.BOPAlgo_AlertBuilderFailed
Error: Building of the result shape has failed

.BOPAlgo_AlertNullFace
Error: The face given to be split is a null shape

.BOPAlgo_AlertNullInputShapes
Error: No or null input shapes

.BOPAlgo_AlertPostTreatFF
Error: Cannot connect face intersection curves

.BOPAlgo_AlertEmptyShape
Warning: Some of the arguments are empty shapes

.BOPAlgo_AlertSelfInterferingShape
Warning: Some of the arguments are self-interfering shapes

.BOPAlgo_AlertTooSmallEdge
Warning: Some edges are too small and have no valid range

.BOPAlgo_AlertNotSplittableEdge
Warning: Some edges are very small and have such a small valid range, that they cannot be split

.BOPAlgo_AlertBadPositioning
Warning: The positioning of the shapes leads to creation of the small edges without valid range

.BOPAlgo_AlertShellSplitterFailed
Warning: Unable to build loops from the given faces

.BOPAlgo_AlertRemovalOfIBForMDimShapes
Warning: Removal of internal boundaries among the multi-dimensional shapes is not supported yet

.BOPAlgo_AlertRemovalOfIBForSolidsFailed
Warning: Removal of internal boundaries among Solids has failed

.BOPAlgo_AlertRemovalOfIBForFacesFailed
Warning: Removal of internal boundaries among Faces has failed

.BOPAlgo_AlertRemovalOfIBForEdgesFailed
Warning: Removal of internal boundaries among Edges has failed
