# Source files for GeomBndLib package
set(OCCT_GeomBndLib_FILES_LOCATION "${CMAKE_CURRENT_LIST_DIR}")

set(OCCT_GeomBndLib_FILES
  GeomBndLib_BezierCurve.cxx
  GeomBndLib_BezierCurve.hxx
  GeomBndLib_BezierCurve2d.cxx
  GeomBndLib_BezierCurve2d.hxx
  GeomBndLib_BezierSurface.cxx
  GeomBndLib_BezierSurface.hxx
  GeomBndLib_BSplineCurve.cxx
  GeomBndLib_BSplineCurve.hxx
  GeomBndLib_BSplineCurve2d.cxx
  GeomBndLib_BSplineCurve2d.hxx
  GeomBndLib_BSplineSurface.cxx
  GeomBndLib_BSplineSurface.hxx
  GeomBndLib_Circle.cxx
  GeomBndLib_Circle.hxx
  GeomBndLib_Circle2d.cxx
  GeomBndLib_Circle2d.hxx
  GeomBndLib_Cone.cxx
  GeomBndLib_Cone.hxx
  GeomBndLib_Curve.cxx
  GeomBndLib_Curve.hxx
  GeomBndLib_Curve2d.cxx
  GeomBndLib_Curve2d.hxx
  GeomBndLib_Cylinder.cxx
  GeomBndLib_Cylinder.hxx
  GeomBndLib_Ellipse.cxx
  GeomBndLib_Ellipse.hxx
  GeomBndLib_Ellipse2d.cxx
  GeomBndLib_Ellipse2d.hxx
  GeomBndLib_Hyperbola.cxx
  GeomBndLib_Hyperbola.hxx
  GeomBndLib_Hyperbola2d.cxx
  GeomBndLib_Hyperbola2d.hxx
  GeomBndLib_InfiniteHelpers.pxx
  GeomBndLib_Line.hxx
  GeomBndLib_Line2d.hxx
  GeomBndLib_OffsetCurve.cxx
  GeomBndLib_OffsetCurve.hxx
  GeomBndLib_OffsetCurve2d.cxx
  GeomBndLib_OffsetCurve2d.hxx
  GeomBndLib_OffsetSurface.cxx
  GeomBndLib_OffsetSurface.hxx
  GeomBndLib_OptimizationHelpers.pxx
  GeomBndLib_OtherCurve.cxx
  GeomBndLib_OtherCurve.hxx
  GeomBndLib_OtherCurve2d.cxx
  GeomBndLib_OtherCurve2d.hxx
  GeomBndLib_OtherSurface.cxx
  GeomBndLib_OtherSurface.hxx
  GeomBndLib_Parabola.cxx
  GeomBndLib_Parabola.hxx
  GeomBndLib_Parabola2d.cxx
  GeomBndLib_Parabola2d.hxx
  GeomBndLib_Plane.hxx
  GeomBndLib_SamplingHelpers.pxx
  GeomBndLib_SplineHelpers.pxx
  GeomBndLib_Sphere.cxx
  GeomBndLib_Sphere.hxx
  GeomBndLib_Surface.cxx
  GeomBndLib_Surface.hxx
  GeomBndLib_SurfaceOfExtrusion.cxx
  GeomBndLib_SurfaceOfExtrusion.hxx
  GeomBndLib_SurfaceOfRevolution.cxx
  GeomBndLib_SurfaceOfRevolution.hxx
  GeomBndLib_Torus.cxx
  GeomBndLib_Torus.hxx
)
