name: 'Upload vcpkg Cache'
description: 'Upload vcpkg installed packages and cache for reuse'

inputs:
  artifact-name:
    description: 'Name of the artifact to store vcpkg cache'
    required: true
  build-directory:
    description: 'Build directory containing vcpkg_installed'
    required: false
    default: 'build'

runs:
  using: "composite"
  steps:

    - name: Upload vcpkg runtime files
      uses: actions/upload-artifact@v4.4.3
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ inputs.build-directory }}/vcpkg_installed/**/*
          !${{ inputs.build-directory }}/vcpkg_installed/**/debug/**
          !${{ inputs.build-directory }}/vcpkg_installed/**/*.pdb
          !${{ inputs.build-directory }}/vcpkg_installed/**/*.lib
        retention-days: 7
        compression-level: 6
