# This workflow will build OCCT on Linux with GCC x64 dynamic
# using the provided Docker image with GCC tools.
#
# Notes:
# freetype is disabled
# samples are not built

name: Build OCCT on Linux with GCC x64 dynamic

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-linux-gcc:
    name: Build on Ubuntu with GCC
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y tcl-dev tk-dev cmake gcc g++ make libbtbb-dev libx11-dev libglu1-mesa-dev

    - name: Configure OCCT
      run: |
        mkdir -p build
        cd build
        cmake -G "Unix Makefiles" \
              -D CMAKE_C_COMPILER=gcc \
              -D CMAKE_CXX_COMPILER=g++ \
              -D USE_FREETYPE=OFF \
              -D CMAKE_BUILD_TYPE=Release \
              -D CMAKE_C_FLAGS="-Werror" \
              -D CMAKE_CXX_FLAGS="-Werror" ..

    - name: Build OCCT
      run: |
        cd build
        make -j$(nproc)
